/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export type AMSActivitiesGetGetGroupTypeEntitysParams = {
'getGroupTypeEntity.attributeCode'?: string;
'getGroupTypeEntity.category'?: number;
'getGroupTypeEntity.description'?: string;
'getGroupTypeEntity.type'?: string;
'getGroupTypeEntity.isHide'?: boolean;
'getGroupTypeEntity.id'?: number;
'getGroupTypeEntity.permanentFlag'?: number;
'getGroupTypeEntity.sortNumber'?: number;
};
