/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export type AMSActivityReferenceGroupsAddActivityGroupParams = {
'activityReferenceGroups.refGrId'?: string;
'activityReferenceGroups.activityCount'?: string;
'activityReferenceGroups.changedBy'?: string;
'activityReferenceGroups.changedByShortName'?: string;
'activityReferenceGroups.changedDate'?: string;
'activityReferenceGroups.enteredDate'?: string;
'activityReferenceGroups.entityId'?: string;
'activityReferenceGroups.entityType'?: number;
'activityReferenceGroups.groupType'?: string;
'activityReferenceGroups.isActive'?: boolean;
'activityReferenceGroups.name'?: string;
'activityReferenceGroups.isHide'?: string;
};
