/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export type AMSClaimsAddAMSClaimParams = {
'aMSClaim.effectiveDate'?: string;
'aMSClaim.lineOfBusinessId'?: string;
'aMSClaim.policyId'?: string;
'aMSClaim.sClaimsMadeId'?: string;
'aMSClaim.answer3'?: boolean;
'aMSClaim.answer4'?: boolean;
'aMSClaim.entryDate'?: string;
'aMSClaim.proposedRetroactiveDate'?: string;
'aMSClaim.remarks'?: string;
'aMSClaim.status'?: string;
};
