/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export type AMSRecentCustomerGetCUstomerByIDParams = {
'AMSRecentCustomer.customerId'?: string;
'AMSRecentCustomer.customerName'?: string;
'AMSRecentCustomer.customerNumber'?: string;
'AMSRecentCustomer.employeeCode'?: string;
'AMSRecentCustomer.isCustomerActive'?: boolean;
'AMSRecentCustomer.lastAccessedDate'?: string;
};
