/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelModelAMSCustomerLossHistory {
  AmountPaid?: number;
  ClaimId?: string;
  ClaimNo?: string;
  ClaimStatus?: string;
  ClosedDate?: string;
  CLossHistId?: string;
  Company?: string;
  CustomerId?: string;
  DateOfLoss?: string;
  EmployeeName?: string;
  KindOfLoss?: string;
  LineOfBusiness?: string;
  LineOfBusinessDescription?: string;
  LossDescCLHis?: string;
  ModificationFactor?: number;
  PolicyEffectiveDate?: string;
  PolicyExpireDate?: string;
  PolicyNumber?: string;
  PolicyYear?: string;
  ReportDate?: string;
}
