/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesCoinsured {
  BusinessAreaCode?: string;
  BusinessExtension?: string;
  BusinessPhone?: string;
  CellAreaCodeCoIns?: string;
  CellExtensionCoIn?: string;
  CellPhoneCoIn?: string;
  CoInsuredId?: string;
  CurrentOccuranceSince?: string;
  DateOfBirth?: string;
  EffectiveDate?: string;
  EmailCoIn?: string;
  EmployerAddr1?: string;
  EmployerAddr2?: string;
  EmployerCity?: string;
  EmployerName?: string;
  EmployerState?: string;
  EmployerZipCode?: string;
  FaxAreaCodeCoIn?: string;
  FaxExtensionCoIn?: string;
  FaxPhoneCoIn?: string;
  FirstName?: string;
  LastName?: string;
  Married?: string;
  MidName?: string;
  Occupation?: string;
  PolicyId?: string;
  ResidentialAreaCode?: string;
  ResidentialExtension?: string;
  ResidentialPhone?: string;
  SSN?: string;
  Status?: string;
  YearEmployed?: string;
  YearsPriorEmployer?: number;
}
