/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialUmbrellaLiability {
  Carrier?: string;
  Description?: string;
  EffectiveDate?: string;
  iLimit1?: number;
  iLimit2?: number;
  iLimit3?: number;
  iLimit4?: number;
  iLimit5?: number;
  iLimit6?: number;
  IsClaimsMade?: boolean;
  LiabilityPolicyType?: string;
  LineOfBusinessId?: string;
  OtherType?: string;
  PolicyEffectiveDate?: string;
  PolicyExpirationDate?: string;
  PolicyId?: string;
  PolicyNumber?: string;
  Premium1?: string;
  Premium2?: string;
  Premium3?: string;
  RatingModification1?: string;
  Status?: string;
  UnderlyingPolicyId?: string;
  vLimit1?: string;
  vLimit2?: string;
  vLimit3?: string;
  vLimit4?: string;
  vLimit5?: string;
  vLimit6?: string;
}
