/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesNatureOfBussiness {
  Description?: string;
  EffectiveDate?: string;
  NatureOfBusinessId?: string;
  PolicyId?: string;
  Status?: string;
}
