/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialTotalPremium {
  AttachId?: string;
  AttachType?: number;
  CommercialPremiumTotalId?: string;
  DefaultCoverageOption?: string;
  EffectiveDate?: string;
  LineOfBusinessId?: string;
  PolicyId?: string;
  PremiumTotal?: number;
  Status?: string;
  TotalGroup?: string;
}
