/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSHomeOwnerOperators {
  BoatOperatorId?: string;
  BoatOperatorNo?: string;
  DateOfBirth?: string;
  EffectiveDate?: string;
  Experience?: string;
  FirstName?: string;
  LastName?: string;
  LicenseNo?: string;
  LicenseState?: string;
  LineOfBusinessId?: string;
  MaritalStatus?: string;
  PolicyId?: string;
  Sex?: string;
  SSN?: string;
  Status?: string;
}
