/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPolicies {
  AgencyBusinessClassification?: string;
  AgencyNotationId?: string;
  BillAccountingNumber?: string;
  BillMethod?: string;
  BrokerCode?: string;
  ChangedBy?: string;
  CompanyCode?: string;
  CompanyCustomerNumber?: string;
  CompanyName?: string;
  CompanyType?: string;
  CompanyUrl?: string;
  CsrCode?: string;
  CustomerId?: string;
  Description?: string;
  EffectiveDate?: string;
  ExecCode?: string;
  ExpiryDate?: string;
  FlatAmount?: number;
  FullTermPremium?: number;
  GLBranchCode?: string;
  GLDepartmentCode?: string;
  GLDivisionCode?: string;
  GLGroupCode?: string;
  IsContinuous?: boolean;
  IsExclDelete?: boolean;
  IsFinanced?: boolean;
  IsMultiEntity?: boolean;
  IsNewBusinessPolicy?: boolean;
  IsWritingCompanyLogoAvailable?: boolean;
  LineOfBusinessIDs?: string;
  MasterAgencyCode?: string;
  MaxEffectiveDatePolicyTransaction?: string;
  Method?: string;
  MultiEntityARFlag?: string;
  NationalProducerCode?: number;
  NegotiatedCommissionsValidDate?: string;
  Notation?: string;
  ParentCompany?: string;
  PaymentPlanId?: string;
  Percentage?: number;
  PolicyId?: string;
  PolicyNumber?: string;
  PolicySubType?: string;
  PolicyType?: string;
  PolicyTypeLOB?: string;
  PremiumAdjustment?: string;
  PriorPolicy?: string;
  PriorPolicyId?: string;
  RenewalReportFlag?: string;
  SourcePolicyId?: string;
  Status?: string;
  SubAgentCode?: string;
  TotalCost?: string;
  TransactNowButton?: boolean;
  TypeOfBusiness?: number;
  TypeOfBusinessDisplay?: string;
  UILineOfBusinessCodes?: string;
  Underwriter?: string;
  WritingCompanyCode?: string;
  WritingCompanyName?: string;
}
