/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelPortfolioSummaryRating {
  CreatedBy?: number;
  CustomerID?: number;
  CustomRate?: number;
  dblPremiumSubtotal?: number;
  dblPremiumSubtotal1?: number;
  dblPremiumSubtotal2?: number;
  dblPremiumSubtotal3?: number;
  dblPremiumSubtotal4?: number;
  DeductibleID1?: number;
  DeductibleID2?: number;
  DeductibleID3?: number;
  DeductibleID4?: number;
  intDeductibleID?: number;
  intLiabilityID?: number;
  intValuationTypeID?: number;
  IsCustomRating?: number;
  ModifiedBy?: number;
  PREMIUMTAX?: number;
}
