/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSEmployeeNotes {
  EmployeeCode?: string;
  IsAttachment?: boolean;
  IsNoteTruncated?: boolean;
  IsSticky?: boolean;
  Note?: string;
  NoteDate?: string;
  NoteId?: string;
  Priority?: string;
  PurgeDate?: string;
}
