/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelModelAMSDependents {
  BusinessAreaCode?: string;
  BusinessExtension?: string;
  BusinessPhone?: string;
  CustomerId?: string;
  DateOfBirth?: string;
  DependentId?: string;
  DriversLicenses?: string;
  Email?: string;
  FaxAreaCode?: string;
  FaxExtension?: string;
  FaxPhone?: string;
  FirstName?: string;
  LastName?: string;
  MaritalStatus?: string;
  MiddleName?: string;
  MobileAreaCode?: string;
  MobileExtension?: string;
  MobilePhone?: string;
  Occupation?: string;
  PagerAreaCode?: string;
  PagerExtension?: string;
  PagerPhone?: string;
  RelationToApplicant?: string;
  ResidenceAreaCode?: string;
  ResidenceExtension?: string;
  ResidencePhone?: string;
  SocialSecurityNumber?: string;
  YearEmployed?: string;
}
