/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialUmbrellaGeneralLiability {
  Answer1?: string;
  Answer2?: string;
  Answer4?: string;
  Answer5?: string;
  Answer6EffectiveDate?: string;
  EffectiveDate?: string;
  IsAnswer3?: boolean;
  IsAnswer6?: boolean;
  LineOfBusinessId?: string;
  PolicyId?: string;
  Status?: string;
  UnderlyingGeneralLiabilityId?: string;
}
