/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesTransaction {
  BillMethodPolicyTransaction?: string;
  Description?: string;
  EffectiveDate?: string;
  EnteredDate?: string;
  EstRevenuePercent?: number;
  PaymentPlanId?: string;
  PolicyId?: string;
  PremiumOnEffectivDate?: number;
  ReasonPolicyTransaction?: string;
  Source?: string;
  SourceDescription?: string;
  TransactionType?: string;
}
