/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialValueReporting {
  AcquiredLocation?: string;
  AggregateLimit?: number;
  BuildingNumber?: string;
  DeclaredLocation?: string;
  EffectiveDate?: string;
  LineOfBusinessId?: string;
  PolicyId?: string;
  PremiseInfoId?: string;
  PremiseNumber?: string;
  Premises?: string;
  PremisesLimit?: number;
  Status?: string;
  SubjectOfInsurance?: string;
  ValueReportingId?: string;
}
