/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSGarageLocation {
  AddressLine1?: string;
  AddressLine2?: string;
  AttachmentId?: string;
  AttachmentType?: number;
  City?: string;
  CommercialLocationId?: string;
  Description?: string;
  EffectiveDate?: string;
  GarageId?: string;
  GarageNumber?: string;
  InlandMarineLocationId?: string;
  LineOfBusinessId?: string;
  PolicyId?: string;
  State?: string;
  Status?: string;
  TaxCode?: string;
  ZipCode?: string;
}
