/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSpoliciesForms {
  AttachId?: string;
  AttachType?: number;
  CFormId?: string;
  Description?: string;
  Description2?: string;
  EditionDate?: string;
  EffectiveDate?: string;
  FormNumber?: string;
  LineOfBusinessId?: string;
  PolicyId?: string;
  Status?: string;
}
