/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesPersonal {
  CommissionMethod?: string;
  CommissionPercentage?: number;
  EffectiveDate?: string;
  EmployeeCode?: string;
  EmployeeType?: string;
  FeeFlatAmount?: number;
  FeeMethod?: string;
  FeePercentage?: number;
  FirstName?: string;
  FlatAmount?: number;
  IsActive?: boolean;
  IsPrimary?: boolean;
  LastName?: string;
  NegotiatedCommissionFieldScope?: string;
  PolicyId?: string;
  PolicyPersonnelId?: string;
}
