/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelWritingCompanyProduct {
  BrokerDescription?: string;
  BrokerID?: number;
  BrokerName?: string;
  ContactID?: number;
  CREATEDATE?: string;
  CreatedBy?: number;
  email?: string;
  FirstName?: string;
  ID?: number;
  LastName?: string;
  ModifiedBy?: number;
  MODIFYDATE?: string;
  ProductDescription?: string;
  ProductID?: number;
  ProductName?: string;
  WritingCompanyDescription?: string;
  WritingCompanyId?: number;
  WritingCompanyName?: string;
}
