/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelModelAuthtoken {
  access_token?: string;
  expires_in?: string;
  refresh_token?: string;
  scope?: string;
  token_type?: string;
  VimCustomer?: string;
  VimEmail?: string;
  VimInstance?: string;
  VimUser?: string;
}
