/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelVMUnderwriter {
  BrokerID?: number;
  BrokerName?: string;
  ContactID?: number;
  CREATEDATE?: string;
  CreatedBy?: number;
  Email?: string;
  FirstName?: string;
  ID?: number;
  LastName?: string;
  ModifiedBy?: number;
  MODIFYDATE?: string;
  Phone?: string;
  WritingCompanyID?: number;
  WritingCompanyName?: string;
}
