/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesSubCustomer {
  Active?: boolean;
  Address1?: string;
  Address2?: string;
  City?: string;
  CustomerId?: string;
  DBA?: string;
  EffectiveDate?: string;
  FullName?: string;
  InsuredType?: string;
  PolicyId?: string;
  PolicySubCustomerId?: string;
  State?: string;
  Status?: string;
  ZipCode?: string;
}
