/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelModelsGarageAndDealerActionDropDownCoverages } from './domainModelModelsGarageAndDealerActionDropDownCoverages';
import type { DomainModelModelsGarageAndDealerActionDropDownDeductibleTypes } from './domainModelModelsGarageAndDealerActionDropDownDeductibleTypes';
import type { DomainModelModelsFormSections } from './domainModelModelsFormSections';
import type { DomainModelModelsGarageKeepersTypes } from './domainModelModelsGarageKeepersTypes';
import type { DomainModelModelsGarageRiskCodes } from './domainModelModelsGarageRiskCodes';
import type { DomainModelModelsGarageAndDealerActionDropDownMaritalStatuses } from './domainModelModelsGarageAndDealerActionDropDownMaritalStatuses';
import type { DomainModelModelsPhysicalDamagePeriods } from './domainModelModelsPhysicalDamagePeriods';
import type { DomainModelModelsSex } from './domainModelModelsSex';
import type { DomainModelModelsGarageAndDealerActionDropDownStates } from './domainModelModelsGarageAndDealerActionDropDownStates';
import type { DomainModelModelsTypeOfFacilities } from './domainModelModelsTypeOfFacilities';

export interface DomainModelModelsAMSGarageAndDealerActionDropDown {
  Coverages?: DomainModelModelsGarageAndDealerActionDropDownCoverages[];
  DeductibleTypes?: DomainModelModelsGarageAndDealerActionDropDownDeductibleTypes[];
  FormSections?: DomainModelModelsFormSections[];
  GarageKeepersTypes?: DomainModelModelsGarageKeepersTypes[];
  GarageRiskCodes?: DomainModelModelsGarageRiskCodes[];
  MaritalStatuses?: DomainModelModelsGarageAndDealerActionDropDownMaritalStatuses[];
  PhysicalDamagePeriods?: DomainModelModelsPhysicalDamagePeriods[];
  Sex?: DomainModelModelsSex[];
  States?: DomainModelModelsGarageAndDealerActionDropDownStates[];
  TypeOfFacilities?: DomainModelModelsTypeOfFacilities[];
}
