/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSEmployeeExpiringPolicies {
  Actions?: string;
  AssignDate?: string;
  AssignTo?: string;
  BillMethod?: string;
  BrokerCode?: string;
  BrokerName?: string;
  Comments?: string;
  CompanyCode?: string;
  CompanyName?: string;
  CustomerId?: string;
  CustomerName?: string;
  DescriptionBasicPolicy?: string;
  ExecutiveCode?: string;
  ExecutiveName?: string;
  GroupNo?: string;
  IsBackUpPolicy?: boolean;
  IsComplete?: boolean;
  IsCustomerActive?: boolean;
  IsDownLoadPolicy?: boolean;
  IsSecured?: boolean;
  IsSecuredCustomer?: boolean;
  IsSecuredRenewedPolicy?: boolean;
  MaxEffectiveDatePolicyTransaction?: string;
  MaxEffectiveDateRenewalPolicyTransaction?: string;
  PolicyEffectiveDate?: string;
  PolicyExpiryDate?: string;
  PolicyId?: string;
  PolicyNo?: string;
  PolicyOrigin?: string;
  PolicyStatus?: string;
  PolicySubType?: string;
  PolicyType?: string;
  PolicyTypeLineOfBusiness?: string;
  PolicyTypeValue?: string;
  RenewalListPolicyId?: string;
  RenewalPolicyEffectiveDate?: string;
  RenewalPolicyExpiryDate?: string;
  RenewalPolicyId?: string;
  RenewalPolicyNo?: string;
  RepresentativeCode?: string;
  RepresentativeName?: string;
  RunDate?: string;
  Stage?: string;
  StageCode?: string;
  SubmissionGroupId?: string;
  TotalCost?: number;
  TypeOfBusiness?: number;
  TypeOfBusinessDisplay?: string;
  UILineOfBusinessCode?: string;
  WritingCompanyCode?: string;
  WritingCompanyName?: string;
}
