/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelBechmarkUserGroupMember {
  AccountID?: number;
  CREATEDATE?: string;
  CreatedBy?: number;
  Id?: number;
  ModifiedBy?: number;
  MODIFYDATE?: string;
  UserGroupId?: string;
  UserId?: string;
}
