/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSBussinessinformation {
  CarPercent?: string;
  DealerOtherDescription?: string;
  DealerOtherPercent?: string;
  EffectiveDate?: string;
  GaragaAndDealerBusinessInformationId?: string;
  IsCommercialDealer?: boolean;
  IsFranchised?: boolean;
  IsMobileHomeTrailerDealer?: boolean;
  IsOther?: boolean;
  IsRepairShop?: boolean;
  IsServiceStation?: boolean;
  IsStorageGarage?: boolean;
  LineOfBusinessId?: string;
  MotorCyclePercent?: string;
  OtherDescription?: string;
  PolicyId?: string;
  RecreationalVehiclePercent?: string;
  SnowMobilePercent?: string;
  Status?: string;
  TruckPercent?: string;
}
