/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialLinesCoverages {
  Acre?: string;
  AttachId?: string;
  AttachType?: number;
  CLocationId?: string;
  Code?: string;
  CoinsuredPercent?: string;
  Cost?: number;
  Coverage?: string;
  CoverageGroup?: string;
  CoverageLevel?: string;
  CoveragePremiumId?: string;
  CrimeRateGroup?: string;
  DaysPerRestoration?: string;
  Deductible2?: number;
  Deductible3?: number;
  DeductibleAppliesTo?: string;
  DeductibleBasis?: string;
  DeductibleDiscPremium?: number;
  Deductibles?: number;
  DeductibleType?: string;
  DeductibleType2?: string;
  DeductibleType3?: string;
  EffectiveDate?: string;
  EmployeeBenefitRemarks?: string;
  EmployeesCovered?: string;
  EquipmentLevel?: string;
  Exposure?: string;
  FormsCondition?: string;
  Franchise?: string;
  FullTimeEmployees?: string;
  iLimit1?: number;
  iLimit2?: number;
  iLimit3?: number;
  iLimit4?: number;
  InflationGuard?: string;
  InsertSequenceNumber?: number;
  InsuredLossParticipationPercent?: number;
  IsCommunication?: boolean;
  IsContributionLocation?: boolean;
  IsInservant?: boolean;
  IsLeaderLocation?: boolean;
  IsManufacturingLocation?: boolean;
  IsOnApp?: boolean;
  IsOutservant?: boolean;
  IsPower?: boolean;
  IsRecipientLocation?: boolean;
  IsRefrigerationMaintenance?: boolean;
  IsSeasonal?: boolean;
  IsWater?: boolean;
  LimitLossPayment?: string;
  LineOfBusinessId?: string;
  LocationNumber?: string;
  LocationNumberScheduleHazard?: string;
  Miscellaneous?: string;
  NumberOfDays?: string;
  NumberOfHead?: string;
  NumberOfPersonsInDayCare?: boolean;
  PartTimeEmployees?: string;
  Payroll?: number;
  PolicyId?: string;
  Premium?: number;
  Rate?: number;
  RatingBasis?: string;
  Receipts?: number;
  ResidentEmployees?: string;
  RetroactiveDate?: string;
  Sales?: number;
  SortNo?: number;
  State?: string;
  Status?: string;
  Territory?: string;
  TotalAssetValue?: number;
  Type?: string;
  ValuationType?: string;
  VehicleNumber?: string;
  vLimit1?: string;
  vLimit2?: string;
  vLimit3?: string;
  vLimit4?: string;
  WaitingPeriod?: number;
  Zone?: number;
}
