/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelBechmarkUserGroup {
  AccountID?: number;
  CREATEDATE?: string;
  CreatedBy?: number;
  Description?: string;
  Id?: number;
  ModifiedBy?: number;
  MODIFYDATE?: string;
  Name?: string;
}
