/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesContacts {
  Address1?: string;
  Address2?: string;
  AreaCode?: string;
  AttachId?: string;
  AttachType?: number;
  City?: string;
  County?: string;
  Description?: string;
  EffectiveDate?: string;
  EMail?: string;
  Extension?: string;
  FaxAreaCode?: string;
  FaxExtension?: string;
  FaxPhones?: string;
  FormalSalutation?: string;
  InformalSalutation?: string;
  LineOfBusinessId?: string;
  MobileAreaCode?: string;
  MobileExtension?: string;
  MobilePhone?: string;
  Name?: string;
  PagerAreaCode?: string;
  PagerExtension?: string;
  PagerPhone?: string;
  Phone?: string;
  PolicyContactId?: string;
  PolicyId?: string;
  ReferenceNo?: string;
  ResidenceAreaCode?: string;
  ResidenceExtension?: string;
  ResidencePhone?: string;
  Responsibility?: string;
  State?: string;
  Status?: string;
  Title?: string;
  ZipCode?: string;
}
