/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelChangePassword {
  AgentID?: number;
  CustomerID?: number;
  newPassword?: string;
  oldPassword?: string;
  remarks?: string;
  reNewPassword?: string;
}
