/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesEmployerInformation {
  Address1?: string;
  Address2?: string;
  City?: string;
  CurrentOccupationSince?: string;
  EffectiveDate?: string;
  EmployerId?: string;
  Name?: string;
  PolicyId?: string;
  State?: string;
  Status?: string;
  YearsPriorEmployer?: number;
  ZipCode?: string;
}
