/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelModelAMSCustomerBenefitInfo {
  BusinessDescription?: string;
  BusinessType?: string;
  CustomerId?: string;
  EstimatedRevenue?: number;
  Industry?: string;
  LeadSource?: string;
  NumberOfDependentUnits?: number;
  NumberOfEligibleEmployees?: number;
  NumberOfEmployees?: number;
  SaleProbability?: number;
}
