/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesProducer {
  AuthEmpCode?: string;
  EffectiveDate?: string;
  MailOtherDescription?: string;
  MailPolicyTo?: string;
  PolicyId?: string;
  PolicyProducerId?: string;
  SignatureEmployeeCode?: string;
  Status?: string;
}
