/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSEmployeeRenewList {
  Actions?: string;
  AllowSelectControl?: boolean;
  AssignDate?: string;
  AssignTo?: string;
  AssignToName?: string;
  BillMethod?: string;
  BrokerCode?: string;
  BrokerName?: string;
  BusinessDescription?: string;
  Comments?: string;
  CommentsRenewalListHeader?: string;
  CompanyCode?: string;
  CompanyName?: string;
  CustomerId?: string;
  CustomerName?: string;
  Description?: string;
  DescriptionBasicPolicy?: string;
  DisplayExpiryDate?: string;
  ExecutiveCode?: string;
  ExecutiveName?: string;
  GroupNo?: string;
  IsBackupPolicy?: boolean;
  IsComplete?: boolean;
  IsDownloadPolicy?: boolean;
  IsRenewalCCListPolicy?: boolean;
  IsSecured?: boolean;
  IsSecuredCustomer?: boolean;
  IsSecuredRenewedPolicy?: boolean;
  ListStatus?: string;
  MaxEffectiveDatePolicyTransaction?: string;
  MaxEffectiveDateRenewalPolicyTransaction?: string;
  OriginalRenewalListHeaderId?: string;
  PolicyEffectiveDate?: string;
  PolicyExpiryDate?: string;
  PolicyId?: string;
  PolicyNumber?: string;
  PolicyOrigin?: string;
  RenewalListDetail?: string;
  RenewalListHeaderId?: string;
  RenewalListPolicyId?: string;
  RenewalPolicyEffectiveDate?: string;
  RenewalPolicyExpiryDate?: string;
  RenewalPolicyId?: string;
  RenewalPolicyNo?: string;
  ReportDateFrom?: string;
  ReportDateTo?: string;
  ReportInstanceId?: string;
  RepresentativeCode?: string;
  RepresentativeName?: string;
  ResponsibleEmployeeCode?: string;
  ResponsibleEmployeeName?: string;
  RowType?: number;
  RunDate?: string;
  Stage?: string;
  StageCode?: string;
  SubGroupId?: string;
  TypeOfBus?: number;
}
