/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSRecentCustomer {
  CustomerId?: string;
  CustomerName?: string;
  CustomerNumber?: string;
  EmployeeCode?: string;
  IsCustomerActive?: boolean;
  LastAccessedDate?: string;
}
