/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommenActivity {
  ActivityAction?: string;
  ActivityDate?: string;
  ActivityId?: string;
  ActivityTime?: string;
  ActivityType?: number;
  ActivityTypeId?: string;
  Description?: string;
  EmployeeCode?: string;
}
