/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSEmployeeReassignDocument {
  AgencyDocumentType?: string;
  AssignedByEmployeeCode?: string;
  ClaimId?: string;
  Comment?: string;
  Description?: string;
  DocumentAttachmentId?: string;
  DocumentClassificationId?: string;
  DocumentRoutingId?: string;
  EffectiveDate?: string;
  EmployeeCode?: string;
  EntityId?: string;
  EntityType?: number;
  FileName?: string;
  Index1?: string;
  Index2?: string;
  PolicyId?: string;
}
