/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesPeriorCarriers {
  CellAreaCodeCoIns?: string;
  CellExtensionCoIn?: string;
  ConvertPolEffExp?: string;
  ConvertRetroDate?: string;
  EffectiveDate?: string;
  IsOccurrence?: boolean;
  Limit1?: number;
  Limit10?: number;
  Limit11?: number;
  Limit2?: number;
  Limit3?: number;
  Limit4?: number;
  Limit5?: number;
  Limit6?: number;
  Limit7?: number;
  Limit8?: number;
  Limit9?: number;
  LineOfBusiness?: string;
  LineOfBusinessId?: string;
  ModificationFactor?: number;
  NAICCompCode?: string;
  Other?: string;
  PlanType?: string;
  PolicyEffectiveDate?: string;
  PolicyExpireDate?: string;
  PolicyId?: string;
  PolicyNumber?: string;
  PolicyPriorCarrierId?: string;
  PolicyType?: string;
  Premium?: number;
  PriorCarrierName?: string;
  Producer?: string;
  RetroDate?: string;
  Status?: string;
  vLimit1?: string;
  vLimit10?: string;
  vLimit11?: string;
  vLimit2?: string;
  vLimit3?: string;
  vLimit4?: string;
  vLimit5?: string;
  vLimit6?: string;
  vLimit7?: string;
  vLimit8?: string;
  vLimit9?: string;
  vPremium?: string;
  WithCoSince?: string;
  YearNo?: string;
}
