/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSClaimMade {
  Answer3?: boolean;
  Answer4?: boolean;
  EffectiveDate?: string;
  EntryDate?: string;
  LineOfBusinessId?: string;
  PolicyId?: string;
  ProposedRetroactiveDate?: string;
  Remarks?: string;
  SClaimsMadeId?: string;
  Status?: string;
}
