/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelModelAMSActivities {
  ActivityDate?: string;
  ActivityId?: string;
  ActivityTime?: string;
  ClaimId?: string;
  CompanyCode?: string;
  CompanyName?: string;
  CustomerId?: string;
  DBAction?: string;
  Description?: string;
  EmployeeCode?: string;
  EmployeeFullName?: string;
  EmployeeShortName?: string;
  ExecName?: string;
  IsAttachment?: boolean;
  IsTruncated?: boolean;
  PolicyEffectiveDate?: string;
  PolicyEndEffectiveDate?: string;
  PolicyExpirationDate?: string;
  PolicyId?: string;
  PolicyLineOfBusiness?: string;
  PolicyNumber?: string;
  PolType?: string;
  ReferenceDate?: string;
  ReferenceGroupChangedBy?: string;
  ReferenceGroupChangedDate?: string;
  ReferenceGroupID?: string;
  ReferenceGroupName?: string;
  ReferenceGroupType?: string;
  ReferenceText?: string;
  ReferenceType?: string;
  RepName?: string;
  TranTypeDesc?: string;
  UICodeLOBS?: string;
}
