/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialproperty {
  EffectiveDate?: string;
  LineOfBusinessId?: string;
  PolicyId?: string;
}
