/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSGarageOperation {
  AllOthers1?: number;
  AllOthers1Rate?: number;
  AllOthers2?: number;
  AllOthers2Rate?: number;
  AnnualRenumeration?: number;
  EffectiveDate?: string;
  GarageDealerGarageOperationId?: string;
  GarageId?: string;
  GarageLocationNumber?: string;
  LineOfBusinessId?: string;
  NumberOfDealerPlates?: string;
  NumberOfEmployees?: number;
  NumberOfHoists?: string;
  NumberOfRepairPlates?: string;
  NumberOfTransitPlates?: string;
  PolicyId?: string;
  RegularOperators?: number;
  RegularOperatorsRate?: number;
  Status?: string;
  Under25?: number;
  Under25Rate?: number;
}
