/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesRateDate {
  EffectiveDate?: string;
  InsertSequenceNumber?: number;
  LineOfBusiness?: string;
  PolicyId?: string;
  RateDate?: string;
  RateDateId?: string;
  State?: string;
  Status?: string;
}
