/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelActivityReferenceGroups {
  ActivityCount?: string;
  ChangedBy?: string;
  ChangedByShortName?: string;
  ChangedDate?: string;
  EnteredDate?: string;
  EntityId?: string;
  EntityType?: number;
  GroupType?: string;
  IsActive?: boolean;
  IsHide?: string;
  Name?: string;
  RefGrId?: string;
}
