/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSInvoiceBillToModel {
  AdditionalOtherInterestId?: string;
  AddToAllInstallments?: boolean;
  ARCustomerId?: string;
  BilledToAddress1?: string;
  BilledToAddress2?: string;
  BilledToCity?: string;
  BilledToLoanNo?: string;
  BilledToName1?: string;
  BilledToName2?: string;
  BilledToState?: string;
  BilledToZip?: string;
  BillingHeaderId?: string;
  BillingSeqenceId?: string;
  BillingSource?: string;
  BillingType?: string;
  CommAdditionalOtherInterestId?: string;
  InvoiceBillToId?: string;
  InvoiceDownPaymentAmount?: number;
  InvoiceFinanceAmount?: number;
  InvoiceId?: string;
  InvoiceNonPremiumAmount?: number;
  InvoicePremiumAmount?: number;
  IsPosted?: boolean;
  LastChargeDate?: string;
  MultipleEntitySuffix?: number;
  OriginalPrintDate?: string;
  PostedBy?: string;
  PrintInvoice?: boolean;
  PrintMemoBroker?: boolean;
  PrintMemoInsured?: boolean;
  UpdatePolicyBillingAddress?: boolean;
}
