/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelRecurringSubscription {
  AccountNumber?: string;
  AccountType?: string;
  ADDRESS1?: string;
  ADDRESS2?: string;
  AGENTID?: number;
  Amount?: string;
  ApiLoginID?: string;
  ApiTransactionKey?: string;
  BankName?: string;
  BillingID?: number;
  CardHolderName?: string;
  CardNumber?: string;
  CITY?: string;
  Code?: string;
  COMPANY?: string;
  CreateDate?: string;
  CreditBankID?: number;
  CustomerID?: number;
  CustomerPaymentProfileId?: string;
  CustomerProfileId?: string;
  CustomersEMAIL?: string;
  CustomersFIRSTNAME?: string;
  CustomersLASTNAME?: string;
  CustomersPHONE?: string;
  CVV?: string;
  Description?: string;
  EcheckType?: string;
  EMAIL?: string;
  ExpiryMonth?: string;
  ExpiryYear?: string;
  FIRSTNAME?: string;
  Interval?: number;
  InvoiceID?: string;
  InvoiceNo?: string;
  LASTNAME?: string;
  Message?: string;
  NameOnAccount?: string;
  PASSWORD?: string;
  PaymentMethodName?: string;
  PHONE?: string;
  RecurringID?: number;
  RoutingNumber?: string;
  StartDate?: string;
  STATE?: string;
  STATEID?: number;
  Status?: string;
  SubscriptionId?: string;
  TotalOccurrences?: number;
  TrialAmount?: string;
  UpdatedDate?: string;
  USERNAME?: string;
  ZIPCODE?: string;
}
