/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesRemark {
  AttachId?: string;
  AttachType?: number;
  EffectiveDate?: string;
  IsSaved?: boolean;
  IsUploaded?: boolean;
  LineOfBusinessId?: string;
  PolicyId?: string;
  Remark?: string;
  RemarkId?: string;
  Status?: string;
}
