/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialUniqueAnswer {
  Answer?: string;
  AnswerFormat?: string;
  AnswerLength?: number;
  CompanySpecificQuestionRelationId?: string;
  IsHide?: boolean;
  LineOfBusinessId?: string;
  PolicyId?: string;
  Question?: string;
  QuestionId?: string;
}
