/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialPrmiarylocation {
  Address1?: string;
  Address2?: string;
  AnnualGrossSale?: string;
  AnnualPayroll?: string;
  City?: string;
  CommercialLocationId?: string;
  EffectiveDate?: string;
  ForeignGrossSale?: string;
  LineOfBusinessId?: string;
  Name?: string;
  NumberOfEmployees?: number;
  PolicyId?: string;
  State?: string;
  Status?: string;
  UniqueLocationId?: string;
  UniqueLocationNumber?: string;
  UniqueLocationNumberForm?: string;
  Zip?: string;
}
