/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSEPIMasterForms {
  CustomerId?: string;
  Description?: string;
  DisplayName?: string;
  DisplayVersion?: string;
  ElfFormId?: string;
  EvidenceOfPropertyInformationId?: string;
  EvidenceOfPropertyNumber?: string;
  FormNumber?: string;
  HoldersCount?: number;
  HoldersCountDate?: string;
  IsActive?: boolean;
  IsHidePageData?: boolean;
  IsOnInternet?: boolean;
  IssueDate?: string;
  LastPrintDate?: string;
  LastPrintMethod?: string;
  PageData?: string;
  PageNumber?: number;
  PolicyEffectiveDate?: string;
  PolicyId?: string;
  SortNumber?: number;
}
