/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSInvoicePolicyTransactionsModel {
  BillingHeaderId?: string;
  BillingSequenceId?: string;
  BillingTransactionId?: string;
  CustomerCoAmount?: number;
  CustomerId?: string;
  InvoiceCompanyId?: string;
  InvoiceCustomerPremiumId?: string;
  InvoiceEffectiveDate?: string;
  InvoiceEffectiveText?: string;
  InvoiceId?: string;
  InvoiceTransactionId?: string;
  PolicyCustomerPremiumId?: string;
}
