/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelModelAMSCustomerContacts {
  Address1?: string;
  Address2?: string;
  BusinessAreaCode?: string;
  BusinessExtension?: string;
  BusinessPhone?: string;
  CCntId?: string;
  City?: string;
  ContactName?: string;
  County?: string;
  CustCenterDisplay?: boolean;
  CustomerId?: string;
  EMail?: string;
  FaxAreaCode?: string;
  FaxExtension?: string;
  FaxPhone?: string;
  FormalSalutation?: string;
  InformalSalutation?: string;
  IsDirector?: boolean;
  IsOfficer?: boolean;
  MobileAreaCode?: string;
  MobileExtension?: string;
  MobilePhone?: string;
  PagerAreaCode?: string;
  PagerExtension?: string;
  PagerPhone?: string;
  ResidenceAreaCode?: string;
  ResidenceExtension?: string;
  ResidencePhone?: string;
  SortOrder?: number;
  State?: string;
  Title?: string;
  ZipCode?: string;
}
