/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSInvoiceModel {
  AccountsReceivableClosedDate?: string;
  AccountsReceivableClosedStatus?: string;
  BillingHeaderId?: string;
  BillMethod?: string;
  BinderPolicyTransactionEffectiveDate?: string;
  BinderPostMethod?: string;
  BinderStatus?: string;
  BrokerCode?: string;
  ClosedDate?: string;
  ClosedStatus?: string;
  CustomerId?: string;
  DueDate?: string;
  ExecutiveCode?: string;
  GeneralLedgerBranchCode?: string;
  GeneralLedgerDepartmentCode?: string;
  GeneralLedgerDivisionCode?: string;
  GeneralLedgerGroupCode?: string;
  InvoiceDate?: string;
  InvoiceEffectiveDate?: string;
  InvoiceId?: string;
  InvoiceNumber?: number;
  InvoiceType?: number;
  IsCancelled?: boolean;
  IsInstallment?: boolean;
  IsPosted?: boolean;
  JournalTransactionId?: string;
  OnAccountDescription?: string;
  OnAccountFinanceCode?: string;
  OnAccountOrigin?: number;
  OriginalDueDate?: string;
  OriginalInvoiceIdInvoice?: string;
  PolicyId?: string;
  PolicyNumber?: string;
  PolicyRelation?: string;
  RepresentativeCode?: string;
  VoidInvoiceIdInvoice?: string;
}
