/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelAMSModelGroups } from './domainModelAMSModelGroups';

export interface DomainModelAMSModelDepartments {
  ChangedDate?: string;
  Groups?: DomainModelAMSModelGroups[];
  IsHidden?: boolean;
  ItemCode?: string;
  ItemCodeHash?: string;
  Name?: string;
  Status?: string;
}
