/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelAMSModelCActionDropDownCoverages } from './domainModelAMSModelCActionDropDownCoverages';
import type { DomainModelAMSModelCActionDropDownDeductibleTypes } from './domainModelAMSModelCActionDropDownDeductibleTypes';
import type { DomainModelAMSModelCActionDropDownDeductibleStates } from './domainModelAMSModelCActionDropDownDeductibleStates';

export interface DomainModelAMSModelCAMSCmmercialCoveragePremiumActionDropDown {
  Coverages?: DomainModelAMSModelCActionDropDownCoverages[];
  DeductibleTypes?: DomainModelAMSModelCActionDropDownDeductibleTypes[];
  States?: DomainModelAMSModelCActionDropDownDeductibleStates[];
}
