/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSJournalVoucherModel {
  AttachmentId?: string;
  AttachmentType?: number;
  BrokerageCode?: string;
  BrokerCode?: string;
  CommissionPersonalCode?: string;
  CompanyCode?: string;
  CreditAmount?: number;
  CustomerId?: string;
  DebitAmount?: number;
  Description?: string;
  FeeCompanyCode?: string;
  FinanceCode?: string;
  FiscalPeriod?: string;
  FiscalYear?: string;
  GeneralLedgerBrnchCodes?: string;
  GeneralLedgerDepartment?: string;
  GeneralLedgerDivision?: string;
  GeneralLedgerGroupCode?: string;
  GeneralLedgerNumber?: string;
  GeneralLedgerTransactionId?: string;
  GeneralLedgerTransactionType?: number;
  GLSADefine?: number;
  InvoiceCommissionId?: string;
  InvoiceCompanyPremiumIds?: string;
  InvoiceCustomerPremiumId?: string;
  InvoiceId?: string;
  InvoiceTransactionPremiumId?: string;
  IsPosted?: boolean;
  JournalTransactionId?: string;
  PayableCompanyCode?: string;
  PayStatementHeaderId?: string;
  PolicyId?: string;
  RecStatementHeaderId?: string;
  S1099Category?: number;
  S1099CategoryDescription?: string;
  S1099Type?: number;
  S1099TypeDescription?: string;
  SourceJournal?: number;
  SourceReferenceNumber?: number;
  SourceTransaction?: number;
  TransactionDate?: string;
  VendorCode?: string;
  VoucherAmount?: number;
  VoucherDescription?: string;
  VoucherType?: string;
  WaiveLateChargeAmount?: number;
  WaiveSmallBalanceAmount?: number;
}
