/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelModelAMSAssignedEmployees {
  Address?: string;
  AddressLine2?: string;
  AllowMemoCommissions?: boolean;
  BeginningJournalEntryClosedStatus?: string;
  BrokerCode?: string;
  BusinessAreaCode?: string;
  BusinessExtension?: string;
  BusinessPhone?: string;
  CellAreaCode?: string;
  CellExtension?: string;
  CellPhone?: string;
  City?: string;
  DateOfBirth?: string;
  DisplayName?: string;
  Doc360HotFolderLocation?: string;
  Doc360HotSpot?: string;
  EMail?: string;
  EmergencyContactAreaCode?: string;
  EmergencyContactExtension?: string;
  EmergencyContactName?: string;
  EmergencyContactPhone?: string;
  Employee1099Category?: number;
  Employee1099Type?: number;
  EmployeeCode?: string;
  EmployeeCodeHash?: string;
  EmployeeId?: string;
  EmployeeShortName?: string;
  EmployeeStatus?: string;
  EmployeeSupervisorCode?: string;
  EmployeeTitle?: string;
  Executive?: boolean;
  FaxAreaCode?: string;
  FaxExtension?: string;
  FaxPhone?: string;
  FirstName?: string;
  FullTimeOrPartTime?: string;
  HomeAreaCode?: string;
  HomeExtension?: string;
  HomePhone?: string;
  IsAdmin?: boolean;
  IsBUFiltered?: boolean;
  IsHide?: boolean;
  LastName?: string;
  LicensedAgent?: boolean;
  LimitCustomerAccess?: boolean;
  LogDownloadSuspense?: boolean;
  MiddleName?: string;
  NationalProducerCode?: number;
  NetFlag?: boolean;
  PagerAreaCode?: string;
  PagerExtension?: string;
  PagerPhone?: string;
  Representative?: boolean;
  SalesCenterRepresentative?: boolean;
  State?: string;
  TimeZone?: number;
  VimId?: number;
  YearEmployed?: string;
  ZipCode?: string;
}
