/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelModelAMSDocuments {
  AgencyDocTypeDescription?: string;
  ClaimNumberList?: string;
  Description?: string;
  DocumentAttachmentId?: string;
  FileExtension?: string;
  FileName?: string;
  PolicyNumberList?: string;
  ReceivedDate?: string;
  ReferenceNumber?: string;
  StorageOption?: string;
}
