/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelAMSModelsCommercialVehicleTypes } from './domainModelAMSModelsCommercialVehicleTypes';
import type { DomainModelAMSModelsCommercialUmbrellaActionDropDownCompanyNames } from './domainModelAMSModelsCommercialUmbrellaActionDropDownCompanyNames';
import type { DomainModelAMSModelsCommercialUmbrellaActionDropDownCoverages } from './domainModelAMSModelsCommercialUmbrellaActionDropDownCoverages';
import type { DomainModelAMSModelsCommercialUmbrellaActionDropDownDeductibleBasis } from './domainModelAMSModelsCommercialUmbrellaActionDropDownDeductibleBasis';
import type { DomainModelAMSModelsDeductibleTypes } from './domainModelAMSModelsDeductibleTypes';
import type { DomainModelAMSModelsCommercialUmbrellaActionDropDownStates } from './domainModelAMSModelsCommercialUmbrellaActionDropDownStates';
import type { DomainModelAMSModelsUnderlyingLiabilityTypes } from './domainModelAMSModelsUnderlyingLiabilityTypes';

export interface DomainModelAMSModelsAMSCommercialUmbrellaActionDropDown {
  CommercialVehicleTypes?: DomainModelAMSModelsCommercialVehicleTypes[];
  CompanyNames?: DomainModelAMSModelsCommercialUmbrellaActionDropDownCompanyNames[];
  Coverages?: DomainModelAMSModelsCommercialUmbrellaActionDropDownCoverages[];
  DeductibleBasis?: DomainModelAMSModelsCommercialUmbrellaActionDropDownDeductibleBasis[];
  DeductibleTypes?: DomainModelAMSModelsDeductibleTypes[];
  States?: DomainModelAMSModelsCommercialUmbrellaActionDropDownStates[];
  UnderlyingLiabilityTypes?: DomainModelAMSModelsUnderlyingLiabilityTypes[];
}
