/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSEmployeeLosPolicies {
  CancellationDate?: string;
  ClientName?: string;
  CustomerId?: string;
  ExecutiveCode?: string;
  ExecutiveName?: string;
  IsCustomerActive?: boolean;
  PolicyId?: string;
  PolicyNumber?: string;
  PolicyPremium?: number;
  PolicyTypeLOB?: string;
  ReasonForCancellation?: string;
  RepresentativeCode?: string;
  RepresentativeName?: string;
  TotalCost?: number;
  TypeOfBus?: number;
  TypeOfBusDescription?: string;
  WritingCompanyCode?: string;
  WritingCompanyName?: string;
}
