/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesGeneralInformation {
  Answer1?: boolean;
  Answer10?: boolean;
  Answer11?: boolean;
  Answer12?: boolean;
  Answer1b?: boolean;
  Answer2?: boolean;
  Answer3?: boolean;
  Answer4?: boolean;
  Answer5?: boolean;
  Answer6?: boolean;
  Answer7?: boolean;
  Answer8?: boolean;
  Answer9?: boolean;
  EffectiveDate?: string;
  PolicyId?: string;
  Status?: string;
  UnderWritingSignatureId?: string;
}
