/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelPortfolioRating {
  ADDRESS?: string;
  AREA?: number;
  CITY?: string;
  CommissionFee?: number;
  COUNTY?: string;
  CreatedBy?: number;
  CustomerID?: number;
  CustomFloodRate?: number;
  CustomLiability?: number;
  CustomRate?: number;
  dblContentsBasePremium?: number;
  dblContentsPremium?: number;
  dblFee?: number;
  dblFloodPremium?: number;
  dblFloodPremiumTax?: number;
  dblLiabilityPremium?: number;
  dblLiabilityPremiumTax?: number;
  dblPremiumSubtotal?: number;
  dblPremiumTax?: number;
  dblPropertyBasePremium?: number;
  dblPropertyPremium?: number;
  dblRentBasePremium?: number;
  dblRentPremium?: number;
  dblTIVBaseTax?: number;
  dblTotal?: number;
  doubleFeePercentage?: number;
  doubleLongFormFee?: number;
  FEEPREMIUM?: number;
  FinalPremium?: number;
  FLOODCOVERAGE?: number;
  FLOODPREMIUM?: number;
  InspectionFee?: number;
  intDeductibleID?: number;
  intLiabilityID?: number;
  intValuationTypeID?: number;
  intWritingCompanyID?: number;
  IsCustomRating?: number;
  IsFeesWaived?: boolean;
  LiabilityPremium?: number;
  ModifiedBy?: number;
  PremiumOfferedToCustomer?: number;
  PREMIUMSUBTOTAL?: number;
  PREMIUMTAX?: number;
  PROPERTYCOVERAGE?: number;
  PROPERTYID?: number;
  PROPERTYPREMIUM?: number;
  QuoteBaseRate?: number;
  State?: string;
  STATEID?: number;
  WholesaleBaseRate?: number;
  WholesalePremium?: number;
  ZIPCODE?: string;
}
