/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSDealerPhysicalDamage {
  EffectiveDate?: string;
  GarageDealersPhysicalDamageId?: string;
  IsCollisionNew?: boolean;
  IsCollisionUsed?: boolean;
  IsCollisionYes1?: boolean;
  IsCollisionYes2?: boolean;
  IsCollisionYes3?: boolean;
  IsComprehensiveNew?: boolean;
  IsComprehensiveUsed?: boolean;
  IsComprehensiveYes1?: boolean;
  IsComprehensiveYes2?: boolean;
  IsComprehensiveYes3?: boolean;
  IsSpecifiedNew?: boolean;
  IsSpecifiedUsed?: boolean;
  IsSpecifiedYes1?: boolean;
  IsSpecifiedYes2?: boolean;
  IsSpecifiedYes3?: boolean;
  LineOfBusinessId?: string;
  PolicyId?: string;
  Status?: string;
}
