/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelAMSModelAssignedTo } from './domainModelAMSModelAssignedTo';
import type { DomainModelAMSModelCenter } from './domainModelAMSModelCenter';
import type { DomainModelAMSModelDocumentType } from './domainModelAMSModelDocumentType';
import type { DomainModelAMSModelRenewalListStatus } from './domainModelAMSModelRenewalListStatus';
import type { DomainModelAMSModelSecurityClassification } from './domainModelAMSModelSecurityClassification';
import type { DomainModelAMSModelStage } from './domainModelAMSModelStage';

export interface DomainModelAMSModelAMSEmployeeActionDropDown {
  AssignedTo?: DomainModelAMSModelAssignedTo[];
  Center?: DomainModelAMSModelCenter[];
  DocumentType?: DomainModelAMSModelDocumentType[];
  RenewalListStatus?: DomainModelAMSModelRenewalListStatus[];
  SecurityClassification?: DomainModelAMSModelSecurityClassification[];
  Stage?: DomainModelAMSModelStage[];
}
