/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelREOMonthlyBillingReportDto {
  ADDRESS?: string;
  AgencyFee?: number;
  AssetStatusID?: number;
  Balance?: number;
  BillingType?: string;
  BrokerFee?: number;
  CITY?: string;
  CUSTOMERID?: number;
  EffectiveDate?: string;
  ExpirationDate?: string;
  FinalPremium?: number;
  FirstInstallment?: number;
  FIRSTNAME?: string;
  INSUREDNAME?: string;
  LASTNAME?: string;
  PolicyNumber?: string;
  PREMIUMTAX?: number;
  PropertyEffectiveDate?: string;
  PropertyExpirationDate?: string;
  PROPERTYID?: number;
  ReceivedPremium?: number;
  State?: string;
  Taxes?: number;
  WholesalePremium?: number;
  WritingCompanyID?: number;
  WritingCompanyName?: string;
  ZIPCODE?: string;
}
