/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelSamplePresenter {
  ACCOUNTID?: number;
  ADDITIONALINSURED?: string;
  ADDRESS?: string;
  AGENTID?: number;
  AREA?: number;
  BILLINGINSTALLMENTS?: number;
  BILLINGMONTHLYPAYMENT?: number;
  BILLINGOPTIONID?: number;
  CITY?: string;
  CONSTRUCTIONTYPEID?: number;
  CONTENTSCOVERAGE?: number;
  CONTENTSPREMIUM?: number;
  COUNTY?: string;
  COVERAGE?: number;
  CREATEDATE?: string;
  CUSTOMCOVERAGE?: number;
  CUSTOMERID?: number;
  DEDUCTIBLEID?: number;
  FEEPREMIUM?: number;
  FLOODCOVERAGE?: number;
  FLOODPREMIUM?: number;
  INSUREDNAME?: string;
  LIABILITYID?: number;
  LOANNUMBER?: string;
  MODIFYDATE?: string;
  MORTGAGEBILLEDID?: number;
  MORTGAGECOMPANYID?: number;
  OCCUPANCYTYPEID?: number;
  PREMIUMSUBTOTAL?: number;
  PREMIUMTAX?: number;
  PREMIUMTOTAL?: number;
  PROPERTYCOVERAGE?: number;
  PROPERTYID?: number;
  PROPERTYPREMIUM?: number;
  PROPERTYTYPEID?: number;
  PROPERTYUID?: string;
  RENTCOVERAGE?: number;
  SERIALID?: number;
  State?: string;
  STATEID?: number;
  VALUATIONTYPEID?: number;
  YEAR?: number;
  ZIPCODE?: string;
}
