/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelAMSModelSubValue } from './domainModelAMSModelSubValue';

export interface DomainModelAMSModelDivision {
  Key?: string;
  Value?: DomainModelAMSModelSubValue[];
}
