/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPolicyTransactionPremium {
  BilledPremium?: number;
  ChargeCategory?: string;
  CompanyCode?: string;
  CompanyType?: string;
  Description?: string;
  EffectiveDate?: string;
  EstRevenue?: number;
  FullTermPremium?: number;
  HowBilled?: string;
  IncludePremium?: boolean;
  IsCorrected?: boolean;
  IsPosted?: boolean;
  IsSuspended?: boolean;
  LineOfBusiness?: string;
  PlanType?: string;
  PolicyId?: string;
  PolicyTransactionPremiumId?: string;
  Premium?: number;
  Reconciled?: string;
  WritingCompanyCode?: string;
  WrittenPremium?: number;
}
