/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSBroker {
  Address?: string;
  AddressLine2?: string;
  BrokerCode?: string;
  BrokerCodeHash?: string;
  BusinessAreaCode?: string;
  BusinessExtension?: string;
  BusinessPhone?: string;
  City?: string;
  DisplayName?: string;
  EMail?: string;
  EmergencyContactName?: string;
  EmployeeCode?: string;
  EmployeeShortName?: string;
  FaxAreaCode?: string;
  FaxExtension?: string;
  FaxPhone?: string;
  FirstName?: string;
  IsBUFiltered?: boolean;
  IsHide?: boolean;
  LastName?: string;
  MiddleName?: string;
  MobileAreaCode?: string;
  MobileExtension?: string;
  MobilePhone?: string;
  NetFlag?: boolean;
  ResidenceAreaCode?: string;
  ResidenceExtension?: string;
  ResidencePhone?: string;
  State?: string;
  ZipCode?: string;
}
