/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPolicySubmissions {
  AgencyNotationId?: string;
  BillMethod?: string;
  BrokerCode?: string;
  CompanyCode?: string;
  CompanyCustomerNumber?: string;
  CompanyName?: string;
  CompanyType?: string;
  CompanyUrl?: string;
  CsrCode?: string;
  CustomerId?: string;
  Description?: string;
  EffectiveDate?: string;
  ExecCode?: string;
  ExpiryDate?: string;
  FullTermPremium?: number;
  GLBranchCode?: string;
  GLDepartmentCode?: string;
  GLDivisionCode?: string;
  GLGroupCode?: string;
  GroupDate?: string;
  GroupNumber?: string;
  IsContinuous?: boolean;
  IsExclDelete?: boolean;
  IsFinanced?: boolean;
  IsMultiEntity?: boolean;
  IsNewBusinessPolicy?: boolean;
  LineOfBusinessIDs?: string;
  NationalProducersCode?: number;
  ParentCompany?: string;
  PolicyId?: string;
  PolicyNumber?: string;
  PolicySubType?: string;
  PolicyType?: string;
  PolicyTypeLOB?: string;
  PriorPolicy?: string;
  PriorPolicyId?: string;
  RenewalReportFlag?: string;
  SourcePolicyId?: string;
  SubmissionGroupId?: string;
  SubmissionId?: string;
  TypeOfBusiness?: number;
  UILineOfBusinessCodes?: string;
  Underwriter?: string;
  WritingCompany?: string;
  WritingCompanyCode?: string;
}
