/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelAMSModelBranches } from './domainModelAMSModelBranches';

export interface DomainModelAMSModelDivisions {
  Branches?: DomainModelAMSModelBranches[];
  ChangedDate?: string;
  IsHidden?: boolean;
  ItemCode?: string;
  ItemCodeHash?: string;
  Name?: string;
  Status?: string;
}
