/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelModelAMSClaims {
  AdditionalRisk?: string;
  CatastropheCode?: string;
  CauseOfLoss?: string;
  ClaimContactNameList?: string;
  ClaimId?: string;
  ClaimNumber?: string;
  ClaimStatus?: string;
  ClosedDate?: string;
  CustomerId?: string;
  CustomerName?: string;
  Description?: string;
  DisplayNameElff?: string;
  ElfFormId?: string;
  IsCustomerActive?: boolean;
  LineOfBusiness?: string;
  LineOfBusinessId?: string;
  LossDate?: string;
  LossLocationAddress?: string;
  LossLocationCity?: string;
  LossLocationState?: string;
  LossLocationZipCode?: string;
  OccurrenceDate?: string;
  PolicyEffectiveDate?: string;
  PolicyEndDate?: string;
  PolicyExpiredDate?: string;
  PolicyId?: string;
  PolicyNumber?: string;
  PolicyType?: string;
  ReportAuthority?: string;
  ReportBy?: string;
  ReportDate?: string;
  ReportNumber?: string;
  ReportTo?: string;
  UICodeLineOfBusiness?: string;
}
