/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesCommercialLocation {
  AddressLine1?: string;
  AddressLine2?: string;
  AnnualRevenues?: number;
  City?: string;
  CommercialLocationId?: string;
  County?: string;
  EffectiveDate?: string;
  LocationNumber?: string;
  PolicyId?: string;
  State?: string;
  Status?: string;
  ZipCode?: string;
}
