/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelModelAMSCustomerXDates {
  AccountSize?: string;
  AgentName?: string;
  Company?: string;
  CustomerId?: string;
  ExpirationDate?: string;
  InterestLevel?: string;
  LineOfBusiness?: string;
  LineOfBusinessName?: string;
  PolicyNumber?: string;
  Premium?: number;
  Remarks?: string;
  XDATId?: string;
}
