/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelModelBillMethods } from './domainModelModelBillMethods';
import type { DomainModelModelPoliciesActionDropDownEntryBrokers } from './domainModelModelPoliciesActionDropDownEntryBrokers';
import type { DomainModelModelCompanyNames } from './domainModelModelCompanyNames';
import type { DomainModelModelCompanyTypes } from './domainModelModelCompanyTypes';
import type { DomainModelModelEmployeeExecs } from './domainModelModelEmployeeExecs';
import type { DomainModelModelEmployeeReps } from './domainModelModelEmployeeReps';
import type { DomainModelModelPolicyNotations } from './domainModelModelPolicyNotations';
import type { DomainModelModelPolicySubTypes } from './domainModelModelPolicySubTypes';
import type { DomainModelModelPolicyTypes } from './domainModelModelPolicyTypes';
import type { DomainModelModelRenewalReportFlags } from './domainModelModelRenewalReportFlags';
import type { DomainModelModelTypesOfBusiness } from './domainModelModelTypesOfBusiness';
import type { DomainModelModelUnderwriters } from './domainModelModelUnderwriters';

export interface DomainModelModelAMSPoliciesActionDropDownEntry {
  BillMethods?: DomainModelModelBillMethods[];
  Brokers?: DomainModelModelPoliciesActionDropDownEntryBrokers[];
  CompanyNames?: DomainModelModelCompanyNames[];
  CompanyTypes?: DomainModelModelCompanyTypes[];
  EmployeeExecs?: DomainModelModelEmployeeExecs[];
  EmployeeReps?: DomainModelModelEmployeeReps[];
  PolicyNotations?: DomainModelModelPolicyNotations[];
  PolicySubTypes?: DomainModelModelPolicySubTypes[];
  PolicyTypes?: DomainModelModelPolicyTypes[];
  RenewalReportFlags?: DomainModelModelRenewalReportFlags[];
  TypesOfBusiness?: DomainModelModelTypesOfBusiness[];
  Underwriters?: DomainModelModelUnderwriters[];
}
