/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSHosNowMobiles {
  CoVehicleNumber?: string;
  Displacement?: number;
  EffectiveDate?: string;
  Horsepower?: number;
  LineOfBusinessId?: string;
  Make?: string;
  Manufacturer?: string;
  Model?: string;
  PolicyId?: string;
  SerialNumber?: string;
  SnowId?: string;
  Status?: string;
  VehicleNumber?: string;
}
