/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesPreviouceAddress {
  Address1?: string;
  Address2?: string;
  AddressSince?: string;
  City?: string;
  EffectiveDate?: string;
  IsCurrentlyOwned?: boolean;
  IsCurrentlyRented?: boolean;
  PolicyId?: string;
  PreviousAddressId?: string;
  State?: string;
  Status?: string;
  VehiclesInHouse?: string;
  YearsPreviousAddress?: string;
  Zip?: string;
}
