/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelSOVDto {
  ADDITIONALINSURED?: string;
  ADDRESS?: string;
  AnnualPremium?: number;
  AREA?: number;
  CITY?: string;
  ConstructionType?: string;
  CONTENTSCOVERAGE?: number;
  COVERAGE?: string;
  CUSTOMERID?: number;
  EffectiveDate?: string;
  EscrowPay?: string;
  ExpirationDate?: string;
  FinalPremium?: number;
  FIRSTNAME?: string;
  FLOODCOVERAGE?: number;
  InsuredEmail?: string;
  InsuredName?: string;
  InsuredPhone?: string;
  LASTNAME?: string;
  LOANNUMBER?: string;
  MortgageeAddress?: string;
  MortgageeCity?: string;
  MortgageeName?: string;
  MortgageeState?: string;
  MortgageeZipcode?: string;
  NumberOfStories?: number;
  OCCUPATIONTYPE?: string;
  PROPERTYCOVERAGE?: number;
  PropertyDescription?: string;
  PropertyEffectiveDate?: string;
  PropertyExpirationDate?: string;
  PROPERTYTYPE?: string;
  PROPERTYUID?: string;
  RENTCOVERAGE?: number;
  State?: string;
  TIV?: number;
  Units?: number;
  ValuationType?: string;
  VALUATIONTYPEID?: string;
  WholesalePremium?: number;
  YEAR?: number;
  ZIPCODE?: string;
}
