/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialPremiseInformation {
  AlarmContact?: string;
  BuildingCodeGrade?: string;
  BurglarAlarmCertificateNumber?: string;
  BurglarAlarmInstall?: string;
  BurglarAlarmOtherDescription?: string;
  BurglarAlarmType?: string;
  CommercialBuildingId?: string;
  CommercialLocationId?: string;
  ConstructionType?: string;
  Description?: string;
  EffectiveDate?: string;
  ExpirationDate?: string;
  Extent?: string;
  FireAlarmManufacturer?: string;
  FireAlarmType?: string;
  FireCodeNumber?: string;
  FireDistrict?: string;
  FireProtectionType?: string;
  FireStationDistance?: string;
  FrontDistance?: string;
  FrontExposureDistance?: string;
  Grade?: string;
  Heating?: boolean;
  HeatingYear?: string;
  HydrantDistance?: string;
  InlandMarineLocationId?: string;
  IsBoilerPremises?: boolean;
  IsInsuranceElsewhere?: boolean;
  IsSprinklered?: boolean;
  LeftDistance?: string;
  LeftExposureDistance?: string;
  LineOfBusinessId?: string;
  ManufacturingArea?: string;
  MerchandiseArea?: string;
  NumberOfBasements?: string;
  NumberOfGuards?: string;
  NumberOfStories?: string;
  OpenSides?: string;
  OtherCoverages?: string;
  OtherOccupancies?: string;
  OtherUpdate?: boolean;
  OtherUpdateYear?: string;
  Plumbing?: boolean;
  PlumbingYear?: string;
  PolicyId?: string;
  PremiseInformationId?: string;
  ProtectionClass?: string;
  RearDistance?: string;
  RearExposureDistance?: string;
  RightDistance?: string;
  RightExposureDistance?: string;
  Roofing?: boolean;
  RoofingYear?: string;
  RoofType?: string;
  SprinklePercentage?: string;
  Status?: string;
  StructureOtherUpdateYear?: string;
  TaxCode?: string;
  TotalAmount?: string;
  TotalArea?: string;
  TotalItems?: string;
  TotalValues?: string;
  TypeOfBusiness?: string;
  WindClass?: string;
  Wiring?: boolean;
  WiringYear?: string;
  YearBuilt?: string;
}
