/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialCareCoustody {
  CareCustodyControlId?: string;
  DescriptionOfOccupancyOrPersonalProperty?: string;
  DoesOtherLiabilityConditionsExist?: string;
  EffectiveDate?: string;
  HasWaiverOfSubrogation?: string;
  IsHeldHarmless?: string;
  IsNamedInsured?: string;
  IsPersonalProperty?: string;
  IsRealProperty?: string;
  LineOfBusinessId?: string;
  LocationNumber?: number;
  PolicyId?: string;
  PropertyValue?: number;
  SquareFeet?: string;
  Status?: string;
}
