/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelPaymentProcessTransaction {
  AccountNumber?: string;
  AccountType?: string;
  ADDRESS1?: string;
  ADDRESS2?: string;
  AgencyCreditId?: number;
  AGENTID?: number;
  Amount?: string;
  AuthCode?: string;
  BankName?: string;
  CardHolderName?: string;
  CardNumber?: string;
  CITY?: string;
  Code?: string;
  COMPANY?: string;
  CreateDate?: string;
  CreatedBy?: number;
  CustomerID?: number;
  CustomersEMAIL?: string;
  CustomersFIRSTNAME?: string;
  CustomersLASTNAME?: string;
  CustomersPHONE?: string;
  CVV?: string;
  Description?: string;
  EcheckType?: string;
  EMAIL?: string;
  ExpiryMonth?: number;
  ExpiryYear?: number;
  FIRSTNAME?: string;
  ID?: number;
  InvoiceID?: number;
  InvoiceNo?: string;
  LASTNAME?: string;
  Message?: string;
  NameOnAccount?: string;
  PASSWORD?: string;
  PaymentMethodName?: string;
  PaymentProcessorId?: number;
  PaymentTypeId?: number;
  PHONE?: string;
  PropertyId?: number;
  RecurringID?: number;
  RefundExpiryMonth?: string;
  RefundExpiryYear?: string;
  ResponseCode?: string;
  ResultCode?: number;
  RoutingNumber?: string;
  STATE?: string;
  STATEID?: number;
  TransactionNo?: string;
  TransID?: string;
  USERNAME?: string;
  ZIPCODE?: string;
}
