/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSMessagesModel {
  ARCustomerId?: string;
  BillingHeaderId?: string;
  BillingSequenceId?: string;
  InvoiceId?: string;
  InvoiceMessageId?: string;
  IsMessageOnStatement?: boolean;
  Status?: string;
  Text?: string;
}
