/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSVoidinformationModel {
  ApprovedBy?: string;
  Balance?: number;
  DebitAmount?: number;
  EnteredBy?: string;
  GeneralDivCode?: string;
  GeneralJournalId?: string;
  GeneralJournalPostedId?: string;
  GeneralJournalPostReferenceNo?: number;
  GeneralJournalReverseId?: string;
  JournalEntryDate?: string;
  JournalEntryReviewed?: boolean;
  JournalEntryType?: number;
  LinkTransactionId?: string;
  Memo?: string;
  OriginalGeneralJournalId?: string;
  OwnerCode?: string;
  OwnerFlag?: string;
  OwnerId?: string;
  RecurringItemId?: string;
  RecurringIterationNumber?: string;
  RecurringJournalEntries?: boolean;
  ReverseReason?: string;
  WorkStationPostDate?: string;
}
