/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelVMInvoicePropertyDetails {
  Address?: string;
  City?: string;
  County?: string;
  EffectiveDate?: string;
  ElapsedDays?: number;
  FinalPremium?: number;
  ID?: number;
  InvoiceAmount?: number;
  InvoiceID?: number;
  PropertyID?: number;
  State?: string;
  Stateid?: number;
  Zipcode?: string;
}
