/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesCommercialSepplementalNames {
  AlternateAreaCode?: string;
  AlternateExtension?: string;
  AlternatePhone?: string;
  BusinessAreaCode?: string;
  BusinessExtension?: string;
  BusinessPhone?: string;
  CellAreaCodeCNI?: string;
  CellExtensionCNI?: string;
  CellPhoneCNI?: string;
  CommercialNamedInsuredId?: string;
  EffectiveDate?: string;
  EmailCNI?: string;
  EntityType?: string;
  FaxAreaCodeCNI?: string;
  FaxExtensionCNI?: string;
  FaxPhoneCNI?: string;
  InsuredType?: string;
  NamedInsured?: string;
  PolicyId?: string;
  PolicySubCustomerId?: string;
  Status?: string;
}
