/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelAMSModelBranche } from './domainModelAMSModelBranche';
import type { DomainModelAMSModelDepartment } from './domainModelAMSModelDepartment';
import type { DomainModelAMSModelDivision } from './domainModelAMSModelDivision';
import type { DomainModelAMSModelGroup } from './domainModelAMSModelGroup';

export interface DomainModelAMSModelAMSBusinessUnits {
  Branches?: DomainModelAMSModelBranche[];
  Departments?: DomainModelAMSModelDepartment[];
  Divisions?: DomainModelAMSModelDivision[];
  GeneralLedgerBranchCode?: string;
  GeneralLedgerBranchCodeHash?: string;
  GeneralLedgerDepartmentCode?: string;
  GeneralLedgerDepartmentCodeHash?: string;
  GeneralLedgerDivisionCode?: string;
  GeneralLedgerDivisionCodeHash?: string;
  GeneralLedgerGroupCode?: string;
  GeneralLedgerGroupCodeHash?: string;
  Groups?: DomainModelAMSModelGroup[];
  IncludeBranch?: boolean;
  IncludeGroup?: boolean;
}
