/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelModelAMSCustomerServicePersonnels {
  BusinessAreaCode?: string;
  BusinessExtension?: string;
  BusinessPhone?: string;
  CustomerAdditionalPersonnelId?: string;
  CustomerId?: string;
  EMail?: string;
  EmployeeCode?: string;
  FaxAreaCode?: string;
  FaxExtension?: string;
  FaxPhone?: string;
  FirstName?: string;
  HomeAreaCode?: string;
  HomeExtension?: string;
  HomePhone?: string;
  IsPrimary?: boolean;
  LastName?: string;
  MiddleName?: string;
  MobileAreaCode?: string;
  MobileExtension?: string;
  MobilePhone?: string;
  TypeOfBusiness?: number;
  TypeOfEmployee?: string;
}
