/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelModelAlarmContact } from './domainModelModelAlarmContact';
import type { DomainModelModelAlarmTypes } from './domainModelModelAlarmTypes';
import type { DomainModelModelConstructionTypes } from './domainModelModelConstructionTypes';
import type { DomainModelModelCommercialActionDropDownCoverages } from './domainModelModelCommercialActionDropDownCoverages';
import type { DomainModelModelCommercialActionDropDownDeductibleTypes } from './domainModelModelCommercialActionDropDownDeductibleTypes';
import type { DomainModelModelFireAlarmType } from './domainModelModelFireAlarmType';
import type { DomainModelModelFireProtection } from './domainModelModelFireProtection';
import type { DomainModelModelMethodOfDeliveryTypes } from './domainModelModelMethodOfDeliveryTypes';
import type { DomainModelModelPolicyAdditionalInterestTypes } from './domainModelModelPolicyAdditionalInterestTypes';
import type { DomainModelModelRatingTypes } from './domainModelModelRatingTypes';
import type { DomainModelModelRequirements } from './domainModelModelRequirements';
import type { DomainModelModelRoofType } from './domainModelModelRoofType';
import type { DomainModelModelCommercialActionDropDownStates } from './domainModelModelCommercialActionDropDownStates';
import type { DomainModelModelSubjectOfInsurance } from './domainModelModelSubjectOfInsurance';
import type { DomainModelModelTypeOfBusiness } from './domainModelModelTypeOfBusiness';
import type { DomainModelModelValuation } from './domainModelModelValuation';
import type { DomainModelModelWindClass } from './domainModelModelWindClass';

export interface DomainModelModelAMSCommercialActionDropDown {
  AlarmContact?: DomainModelModelAlarmContact[];
  AlarmTypes?: DomainModelModelAlarmTypes[];
  ConstructionTypes?: DomainModelModelConstructionTypes[];
  Coverages?: DomainModelModelCommercialActionDropDownCoverages[];
  DeductibleTypes?: DomainModelModelCommercialActionDropDownDeductibleTypes[];
  FireAlarmType?: DomainModelModelFireAlarmType[];
  FireProtection?: DomainModelModelFireProtection[];
  MethodOfDeliveryTypes?: DomainModelModelMethodOfDeliveryTypes[];
  PolicyAdditionalInterestTypes?: DomainModelModelPolicyAdditionalInterestTypes[];
  RatingTypes?: DomainModelModelRatingTypes[];
  Requirements?: DomainModelModelRequirements[];
  RoofType?: DomainModelModelRoofType[];
  States?: DomainModelModelCommercialActionDropDownStates[];
  SubjectOfInsurance?: DomainModelModelSubjectOfInsurance[];
  TypeOfBusiness?: DomainModelModelTypeOfBusiness[];
  Valuations?: DomainModelModelValuation[];
  WindClass?: DomainModelModelWindClass[];
}
