/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSSystemGeneratedWaivers {
  AttachId?: string;
  AttachType?: number;
  DebitAmount?: number;
  GeneralJournalId?: string;
  GeneralJournalPostReferenceNumber?: number;
  GeneralJournalRelationId?: string;
  GeneralLedgerDivCode?: string;
  JournalEntryType?: number;
}
