/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSInvoicedInstallmentsModel {
  AdditionalOtherInterestId?: string;
  ARCustomerId?: string;
  BilledToName1?: string;
  BillingHeaderId?: string;
  BillingSequenceId?: string;
  BillMethod?: string;
  BillSource?: string;
  BillType?: string;
  BinderPolicyTransactionEffectiveDate?: string;
  BinderStatus?: string;
  BrokerCode?: string;
  CommAdditionalOtherInterestId?: string;
  CustomerId?: string;
  HasMessage?: boolean;
  InvoiceBillToId?: string;
  InvoiceDownPaymentAmount?: number;
  InvoiceEffectiveDate?: string;
  InvoiceFinanceAmount?: number;
  InvoiceId?: string;
  InvoiceNonPremiumAmount?: number;
  InvoiceNumber?: number;
  InvoicePremiumAmount?: number;
  InvoiceType?: number;
  IsBinder?: boolean;
  IsCancelled?: boolean;
  IsInstallment?: boolean;
  IsPosted?: boolean;
  MultipleEntitySuffix?: number;
}
