/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCoverdAutoSymbols {
  AdditionalPipDescription?: string;
  EffectiveDate?: string;
  GarageCoveredAutoSymbolId?: string;
  GarageKeepersOtherCoverage?: string;
  IsAdditionalPip25?: boolean;
  IsAdditionalPip27?: boolean;
  IsCollisionSymbol22?: boolean;
  IsCollisionSymbol23?: boolean;
  IsCollisionSymbol24?: boolean;
  IsCollisionSymbol27?: boolean;
  IsCollisionSymbol28?: boolean;
  IsCollisionSymbol30?: boolean;
  IsCollisionSymbol31?: boolean;
  IsComprehensiveSymbol22?: boolean;
  IsComprehensiveSymbol23?: boolean;
  IsComprehensiveSymbol24?: boolean;
  IsComprehensiveSymbol27?: boolean;
  IsComprehensiveSymbol28?: boolean;
  IsComprehensiveSymbol30?: boolean;
  IsComprehensiveSymbol31?: boolean;
  IsLiabilitySymbol21?: boolean;
  IsLiabilitySymbol22?: boolean;
  IsLiabilitySymbol23?: boolean;
  IsLiabilitySymbol24?: boolean;
  IsLiabilitySymbol27?: boolean;
  IsLiabilitySymbol28?: boolean;
  IsLiabilitySymbol29?: boolean;
  IsMedicalSymbol21?: boolean;
  IsMedicalSymbol22?: boolean;
  IsMedicalSymbol23?: boolean;
  IsMedicalSymbol24?: boolean;
  IsMedicalSymbol27?: boolean;
  IsMedicalSymbol28?: boolean;
  IsMedicalSymbol29?: boolean;
  IsOtherSymbol?: string;
  IsOtherSymbol22?: boolean;
  IsOtherSymbol23?: boolean;
  IsOtherSymbol24?: boolean;
  IsOtherSymbol27?: boolean;
  IsOtherSymbol28?: boolean;
  IsOtherSymbol31?: boolean;
  IsPip25?: boolean;
  IsPip27?: boolean;
  IsSpecifiedPerilsSymbol22?: boolean;
  IsSpecifiedPerilsSymbol23?: boolean;
  IsSpecifiedPerilsSymbol24?: boolean;
  IsSpecifiedPerilsSymbol27?: boolean;
  IsSpecifiedPerilsSymbol28?: boolean;
  IsSpecifiedPerilsSymbol30?: boolean;
  IsSpecifiedPerilsSymbol31?: boolean;
  IsUnderinsuredMotoristSymbol22?: boolean;
  IsUnderinsuredMotoristSymbol23?: boolean;
  IsUnderinsuredMotoristSymbol24?: boolean;
  IsUnderinsuredMotoristSymbol26?: boolean;
  IsUnderinsuredMotoristSymbol27?: boolean;
  IsUnderinsuredMotoristSymbol28?: boolean;
  IsUnderinsuredMotoristSymbol29?: boolean;
  IsUninsuredMotoristSymbol22?: boolean;
  IsUninsuredMotoristSymbol23?: boolean;
  IsUninsuredMotoristSymbol24?: boolean;
  IsUninsuredMotoristSymbol26?: boolean;
  IsUninsuredMotoristSymbol27?: boolean;
  IsUninsuredMotoristSymbol28?: boolean;
  IsUninsuredMotoristSymbol29?: boolean;
  LiabilitySymbolEdit?: string;
  LineOfBusinessId?: string;
  MedicalSymbolDescription?: string;
  PhysicalDamageOtherCoverage?: string;
  PipDescription?: string;
  PolicyId?: string;
  Status?: string;
  UnderinsuredMotoristSymbolDescription?: string;
  UninsuredMotoristSymbolDescription?: string;
}
