/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelSample } from './domainModelSample';

export interface DomainModelUser {
  FirstName?: string;
  LastName?: string;
  Samples?: DomainModelSample[];
  UserId?: number;
}
