/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSAttachments {
  Comments?: string;
  Description?: string;
  Doc360DocumentId?: string;
  DocumentClassificationId?: string;
  DocumentStatus?: string;
  DocumentType?: string;
  DocumentTypeDescription?: string;
  FileExtension?: string;
  FileName?: string;
  Index1?: string;
  Index2?: string;
  ReceivedDate?: string;
  ReferenceNumber?: string;
  SecurityClass?: string;
  SourceFileName?: string;
  StorageLocationDescription?: string;
  StorageLocationOption?: string;
  StorageSize?: number;
}
