/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSLineofbussiness {
  Application?: string;
  ApplicationCreatedDate?: string;
  ApplicationVersion?: string;
  Category?: number;
  CompanyPlanType?: string;
  EffectiveDate?: string;
  ElfFormVersionId?: string;
  EntityLink?: string;
  ExpirationDate?: string;
  LineOfBusiness?: string;
  LineOfBusinessId?: string;
  LineOfBusinessName?: string;
  PolicyId?: string;
  SortNumber?: number;
  StatePlanType?: string;
  UICodeLineOfBusinessSetup?: string;
  WritingCompanyCode?: string;
}
