/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSvehicleInformation {
  BodyType?: string;
  Class?: string;
  CostNew?: number;
  CPremCollDed?: number;
  CPremCompDed?: number;
  CPremLiab?: string;
  CPremPIP?: string;
  CPremSpecDed?: number;
  CPremUMUIM?: string;
  CustVehNo?: string;
  EffectiveDate?: string;
  ExcludeFromAutoUpdate?: string;
  Factor?: number;
  FarthestTerm?: string;
  FarZone?: number;
  FilterClass?: string;
  GarageAddr1?: string;
  GarageAddr2?: string;
  GarageCity?: string;
  GarageId?: string;
  GarageNo?: string;
  GarageState?: string;
  GarageZip?: string;
  GVWGCW?: string;
  HorsepowerOfVehicle?: number;
  IsFleet?: string;
  LineOfBusinessId?: string;
  Make?: string;
  Model?: string;
  NearZone?: number;
  NewUsed?: string;
  PolicyId?: string;
  PrimaryRateFactPD?: number;
  PurchaseDate?: string;
  Radius?: string;
  SeatCP?: string;
  SecondRateFact?: number;
  SIC?: string;
  SpecialClassCode?: number;
  SpecialUse?: string;
  Status?: string;
  SymAge?: string;
  Terr?: string;
  TransOrMTC?: string;
  VehicleId?: string;
  VehicleLicenseNumber?: string;
  VehicleLicenseState?: string;
  VehicleNumber?: string;
  VehicleUsage?: string;
  VehicleYear?: string;
  VIN?: string;
}
