/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelPendingPortfolioSummaryDto {
  AnnualPolicyPremium?: number;
  ContentsCostAnnually?: number;
  CustomRate?: number;
  FloodCostAnnually?: number;
  LiabilityCoverage?: string;
  LORCostAnnually?: number;
  MonthlyPolicyPremium?: number;
  MortgageBilledBalance?: number;
  NumberOfProperties?: number;
  SelfBilledTotalAmount?: number;
  Subtotal?: number;
  TotalMortgageBilledPayment?: number;
  TotalPropertyCoverage?: number;
  TotalSelfBilledBalance?: number;
  TotalSelfBilledPayment?: number;
}
