/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelAMSModelDivisions } from './domainModelAMSModelDivisions';

export interface DomainModelAMSModelAMSAgencyBusinessUnits {
  Divisions?: DomainModelAMSModelDivisions[];
  GeneralLedgerBranchCode?: string;
  GeneralLedgerBranchCodeHash?: string;
  GeneralLedgerDepartmentCode?: string;
  GeneralLedgerDepartmentCodeHash?: string;
  GeneralLedgerDivisionCode?: string;
  GeneralLedgerDivisionCodeHash?: string;
  GeneralLedgerGroupCode?: string;
  GeneralLedgerGroupCodeHash?: string;
  IncludeBranch?: boolean;
  IncludeGroup?: boolean;
}
