/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelTransactionSummaryDto {
  ADDRESS?: string;
  AgencyFee?: number;
  AssetStatusID?: number;
  BillingMethod?: string;
  CITY?: string;
  FinalPremium?: number;
  FirstInstallment?: number;
  FIRSTNAME?: string;
  INSUREDNAME?: string;
  InvoiceID?: number;
  InvoiceNo?: string;
  LASTNAME?: string;
  PaymentDate?: string;
  PaymentMethodName?: string;
  PolicyNumber?: string;
  PREMIUMTAX?: number;
  PropertyEffectiveDate?: string;
  PropertyExpirationDate?: string;
  PROPERTYID?: number;
  ReceivedPremium?: number;
  State?: string;
  Status?: string;
  WholesalePremium?: number;
  WritingCompanyID?: number;
  WritingCompanyName?: string;
  ZIPCODE?: string;
}
