/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelAMSModelDepartments } from './domainModelAMSModelDepartments';

export interface DomainModelAMSModelBranches {
  ChangedDate?: string;
  Departments?: DomainModelAMSModelDepartments[];
  IsHidden?: boolean;
  ItemCode?: string;
  ItemCodeHash?: string;
  Name?: string;
  Status?: string;
}
