/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSFirstNameinsured {
  ApplicantId?: string;
  BusinessPhoneAreaCode?: string;
  BusinessPhoneNo?: string;
  BusinessSinceYear?: string;
  BusinessTimeDayEvening?: string;
  CellPhoneAreaCode?: string;
  CellPhoneExtension?: string;
  CellPhoneNo?: string;
  CRBureauApp?: string;
  DateBusinessStarted?: string;
  DateOfBirth?: string;
  DeclarationNameApp?: string;
  DescOfOpsOtherNamedInsd?: string;
  DUNSNoApp?: string;
  EffectiveDate?: string;
  Email?: string;
  EntityType?: string;
  Extension?: string;
  Fax?: string;
  FaxAreaCode?: string;
  FaxExtension?: string;
  FederalEmployeeNo?: string;
  FirmName?: string;
  FirstName?: string;
  GeneralLiabilityCode?: string;
  HasLosses?: boolean;
  IDNoAssigned?: string;
  InstallOrServicePercentage?: number;
  IsResidenceAddressSameAsMail?: boolean;
  KnownSinceYear?: string;
  LastName?: string;
  MailAddress1?: string;
  MailAddress2?: string;
  MailCity?: string;
  MailCounty?: string;
  MailState?: string;
  MailZip?: string;
  Married?: string;
  MiddleName?: string;
  NAICS?: string;
  NCCINo?: string;
  NoOfMembers?: number;
  NoOfYears?: string;
  Occupation?: string;
  OffPremInstallOrServicePercentage?: number;
  OtherNo?: string;
  PolicyId?: string;
  PolProgRequested?: string;
  ProgramCode?: string;
  ResidenceAddress1?: string;
  ResidenceAddress2?: string;
  ResidenceAreaCode?: string;
  ResidenceCity?: string;
  ResidenceCounty?: string;
  ResidenceDayEvening?: string;
  ResidenceExtension?: string;
  ResidencePhone?: string;
  ResidenceState?: string;
  ResidenceZip?: string;
  SICCode?: string;
  SSN?: string;
  Status?: string;
  TaxCode?: string;
  TypeOfBusiness?: string;
  WebAddress?: string;
  YearEmployed?: string;
}
