/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPolicyPermissions {
  HasAccessToComparePolicy?: boolean;
  HasAccessToCreateNewCopyPolicy?: boolean;
  HasAccessToEndorseCancelPolicy?: boolean;
  HasAccessToPolicyLinks?: boolean;
  HasAccessToViewActivePoliciesPanel?: boolean;
  HasAccessToViewBinderBillPolicy?: boolean;
  HasAccessToViewDecPage?: boolean;
  HasAccessToViewPrevailNetwork?: boolean;
  HasAccessToViewRenewRewritePolicy?: boolean;
  HasAccessToViewTNow?: boolean;
  PolicyDecPageURL?: string;
}
