/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSInvoiceCommissionModel {
  AddToAll?: boolean;
  AgencyCommissionAmount?: number;
  AgencyCommissionMethod?: string;
  AgencyCommissionPercentage?: number;
  BillingHeaderId?: string;
  BillingSequenceId?: string;
  BillingTransactionId?: string;
  BusinessUnitCommissionSplitLink?: string;
  CommissionAmount?: number;
  CommissionPersonCode?: string;
  CommissionPersonName?: string;
  CommissionPersonType?: string;
  CommissionPremiumAmount?: number;
  CommissionStateHeaderId?: string;
  InvoiceCommissionId?: string;
  InvoiceCompanyPremiumId?: string;
  InvoiceId?: string;
  InvoiceSplitTemplateId?: string;
  InvoiceTransactonPremiumId?: string;
  IsActive?: boolean;
  IsDisabledInGrid?: boolean;
  MemoFlag?: boolean;
  Method?: string;
  NetFlag?: boolean;
  OriginalCommissionAmount?: number;
  OriginalMethod?: string;
  OriginalPercentage?: number;
  OriginalStatus?: string;
  OverrideFlag?: boolean;
  Percentage?: number;
  PrimaryFlag?: boolean;
  Status?: string;
}
