/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSReceiptGeneralInformation {
  ApprovedBy?: string;
  BankCode?: string;
  BankNumber?: string;
  CashReceiptDetailId?: string;
  CashReceiptDetailReverseId?: string;
  CashReceiptHeaderId?: string;
  CashType?: string;
  CheckNumber?: string;
  Description?: string;
  EnteredBy?: string;
  IsClosedCashReceiptHeader?: boolean;
  IsDeposited?: boolean;
  JournalTransactionId?: string;
  LinkTransactionId?: string;
  Name?: string;
  NSFGJId?: string;
  OriginalCashReceiptDetailId?: string;
  ReceiptAmount?: number;
  ReceiptDate?: string;
  ReceiptNumber?: number;
  ReceivedFrom?: string;
  ReceivedFromCode?: string;
  ReceivedFromId?: string;
  ReverseReason?: string;
  SourceReferenceNumber?: number;
  ThankYouFlag?: string;
  TypeDescription?: string;
  WorkStationPostDate?: string;
}
