/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelPaymentProcess {
  AccountNumber?: string;
  AccountType?: string;
  ADDRESS1?: string;
  ADDRESS2?: string;
  AGENTID?: number;
  Amount?: number;
  BankName?: string;
  CardHolder?: string;
  CardNumber?: string;
  CITY?: string;
  COMPANY?: string;
  CustomerID?: number;
  CVV?: string;
  Description?: string;
  EcheckType?: string;
  EMAIL?: string;
  ExpiryMonth?: string;
  ExpiryYear?: string;
  FIRSTNAME?: string;
  ID?: number;
  InvoiceID?: string;
  InvoiceNo?: string;
  LASTNAME?: string;
  NameOnAccount?: string;
  PASSWORD?: string;
  PaymentMethodName?: string;
  PHONE?: string;
  RecurringID?: number;
  RoutingNumber?: string;
  StartDate?: string;
  STATE?: string;
  STATEID?: number;
  TokenID?: string;
  USERNAME?: string;
  ZIPCODE?: string;
}
