/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSInvoiceTransactionModel {
  AddToAll?: boolean;
  AgencyCommissionAmount?: number;
  AgencyCommissionFlag?: boolean;
  AgencyCommissionText?: string;
  BackInvoiceTransactionPremiumId?: string;
  BIlledPremium?: number;
  BillingHeaderId?: string;
  BillingSequenceId?: string;
  BillingTransactionId?: string;
  BillMethod?: string;
  BinderPolicyTransactionEffectiveDate?: string;
  BinderPostMethod?: string;
  BinderStatus?: string;
  BrokerCode?: string;
  BrokerCommissionFlag?: boolean;
  ChargeCategory?: string;
  ChargeCode?: string;
  CommissionPayType?: string;
  CompanyCode?: string;
  CompanyType?: string;
  CustomerId?: string;
  Description?: string;
  ExecCommissionFlag?: boolean;
  FullTermPremAmount?: number;
  GLDate?: string;
  GrossAmount?: number;
  InvoiceCompanyPremiumId?: string;
  InvoiceEffectiveDate?: string;
  InvoiceId?: string;
  InvoiceNumber?: number;
  InvoiceTotal?: number;
  InvoiceTransactionPremiumId?: string;
  InvoiceType?: number;
  IsCancelled?: boolean;
  IsInstallment?: boolean;
  IsPosted?: boolean;
  JournalTransactionId?: string;
  LineOfBusiness?: string;
  LOBSBTCharge?: string;
  LOBSBTChargeDescription?: string;
  NewInvoiceTransactionPremiumId?: string;
  NonPremiumRecipient?: string;
  OldInvoiceTransactionPremiumId?: string;
  OriginalInvoiceId?: string;
  PlanType?: string;
  PolicyTransactionEffectiveDate?: string;
  PolicyTransactionPremiumId?: string;
  Premium?: number;
  RepCommissionFlag?: boolean;
  ReplaceDate?: string;
  SalesCenterCommissionFlag?: boolean;
  TieredCommissionId?: string;
  TransactionType?: string;
  WritingCompanyCode?: string;
}
