/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelAMSModelCompany } from './domainModelAMSModelCompany';
import type { DomainModelAMSModelGroupTypes } from './domainModelAMSModelGroupTypes';

export interface DomainModelAMSModelCustomActionsGetDropdowns {
  Companies?: DomainModelAMSModelCompany[];
  groupTypes?: DomainModelAMSModelGroupTypes[];
}
