/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialUmbrellaPolicyInformation {
  CommercialUmbrellaPolicyInformationId?: string;
  CurrentRetroactiveDate?: string;
  EffectiveDate?: string;
  ExpiringPolicyNumber?: string;
  IsDollarYes?: boolean;
  IsUmbrella?: boolean;
  LineOfBusinessId?: string;
  PolicyId?: string;
  ProposedRetroactiveDate?: string;
  Status?: string;
}
