/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAccountReps {
  EmployeeCode?: string;
  EncodedEmployeeCode?: string;
  FirstName?: string;
  FullName?: string;
  IsHide?: boolean;
  LastName?: string;
  VIMUserId?: number;
}
