/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelAMSModelAccountReps } from './domainModelAMSModelAccountReps';
import type { DomainModelAMSModelCustomActionsDropDownBrokers } from './domainModelAMSModelCustomActionsDropDownBrokers';
import type { DomainModelAMSModelBusinessEntities } from './domainModelAMSModelBusinessEntities';
import type { DomainModelAMSModelCustomerNotations } from './domainModelAMSModelCustomerNotations';
import type { DomainModelAMSModelCustomActionsDropDownMaritalStatuses } from './domainModelAMSModelCustomActionsDropDownMaritalStatuses';
import type { DomainModelAMSModelMasterSubTypes } from './domainModelAMSModelMasterSubTypes';
import type { DomainModelAMSModelMoreSearchOption } from './domainModelAMSModelMoreSearchOption';
import type { DomainModelAMSModelCustomActionsDropDownStates } from './domainModelAMSModelCustomActionsDropDownStates';

export interface DomainModelAMSModelAMSCustomActionsDropDown {
  accountReps?: DomainModelAMSModelAccountReps[];
  brokers?: DomainModelAMSModelCustomActionsDropDownBrokers[];
  businessEntities?: DomainModelAMSModelBusinessEntities[];
  customerNotations?: DomainModelAMSModelCustomerNotations[];
  EmployeeCode?: string;
  EncodedEmployeeCode?: string;
  FirstName?: string;
  FullName?: string;
  Genders?: DomainModelAMSModelCustomerNotations[];
  IsHide?: boolean;
  LastName?: string;
  maritalStatuses?: DomainModelAMSModelCustomActionsDropDownMaritalStatuses[];
  masterSubTypes?: DomainModelAMSModelMasterSubTypes[];
  moreSearchOptions?: DomainModelAMSModelMoreSearchOption[];
  states?: DomainModelAMSModelCustomActionsDropDownStates[];
  VIMUserId?: number;
}
