/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialUmbrellaAdditionalExposures {
  AdvertisingLiabilityQuestion2?: boolean;
  AdvertisingLiabilityQuestion3?: boolean;
  AircraftQuestion4?: boolean;
  AnnualCost?: number;
  ApartmentNumberOfDivingBoards?: string;
  ApartmentNumberOfPools?: string;
  ApartmentNumberOfStories?: string;
  ApartmentNumberOfUnits?: string;
  AutoLiabilityQuestion5?: boolean;
  AutoLiabilityQuestion6?: boolean;
  AutoLiabilityQuestion7?: boolean;
  AutoLiabilityQuestion8?: boolean;
  AutoLiabilityQuestion9?: boolean;
  BoatDescription?: string;
  BoatHorsePower?: string;
  BoatLength?: string;
  ConstructionLiabilityQuestion10?: boolean;
  ConstructionLiabilityQuestion11?: string;
  ConstructionLiabilityQuestion12?: string;
  ConstructionLiabilityQuestion13?: boolean;
  ConstructionLiabilityQuestion14?: boolean;
  EffectiveDate?: string;
  EmployeeLiabilityOther1?: boolean;
  EmployeeLiabilityOther2?: string;
  EmployeeLiabilityQuestion15?: boolean;
  EPANumber?: string;
  FELA?: boolean;
  GLPollution?: boolean;
  GLStandardISO?: boolean;
  GLSudden?: boolean;
  GrossSales1Year?: string;
  GrossSales2Year?: string;
  GrossSales3Year?: string;
  IncidentalMalpracticeQuestion17?: boolean;
  IncidentalMalpracticeQuestion18?: boolean;
  IsBoatOwned?: string;
  JonesAct?: boolean;
  LineOfBusinessId?: string;
  MediaUsed?: string;
  NumberOfBeds?: string;
  NumberOfDoctors?: string;
  NumberOfNurses?: string;
  PolicyId?: string;
  PollutionLiabilityQuestion20?: boolean;
  ProductLiabilityQuestion22?: boolean;
  ProductLiabilityQuestion23?: boolean;
  ProductLiabilityQuestion24?: boolean;
  ProductLiabilityQuestion25?: boolean;
  ProductLiabilityQuestion27?: string;
  SeparatePollution?: boolean;
  Status?: boolean;
  StopGap?: boolean;
  UmbrellaAdditionalExposureId?: string;
  WaterLiabilityQuestion28?: boolean;
}
