/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelBusinessProducerProduction {
  AGENTID?: number;
  readonly ClosingRatio?: number;
  Earn?: number;
  FIRSTNAME?: string;
  LASTNAME?: string;
  NumberOfCustomer?: number;
  NumberOfProspects?: number;
  PremiumWon?: number;
}
