/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialumbrellaUnderlyingCoverageExposure {
  AdditionalUnderlyingCoverageInformation?: string;
  EffectiveDate?: string;
  IsAdditionalInterestCoverage?: boolean;
  IsAdditionalInterestExposure?: boolean;
  IsAircraftCoverage?: boolean;
  IsAircraftExposure?: boolean;
  IsAircraftPassengerCoverage?: boolean;
  IsAircraftPassengerExposure?: boolean;
  IsAnyAutoCoverage?: boolean;
  IsCareCustodyControlCoverage?: boolean;
  IsCareCustodyControlExposure?: boolean;
  IsClaimsMade?: boolean;
  IsEmployeeCoverage?: boolean;
  IsEmployeeExposure?: boolean;
  IsForeignCoverage?: boolean;
  IsForeignExposure?: boolean;
  IsGarageCoverage?: boolean;
  IsGarageExposure?: boolean;
  IsLiquorCoverage?: boolean;
  IsLiquorExposure?: boolean;
  IsMedicalCoverage?: boolean;
  IsMedicalExposure?: boolean;
  IsOtherExistingCoverage1?: boolean;
  IsOtherExistingCoverage2?: boolean;
  IsOtherExistingCoverage3?: boolean;
  IsOtherExistingCoverage4?: boolean;
  IsOtherExistingExposure1?: boolean;
  IsOtherExistingExposure2?: boolean;
  IsOtherExistingExposure3?: boolean;
  IsOtherExistingExposure4?: boolean;
  IsPollutionCoverage?: boolean;
  IsPollutionExposure?: boolean;
  IsProfessionalCoverage?: boolean;
  IsProfessionalExposure?: boolean;
  IsVendorCoverage?: boolean;
  IsVendorExposure?: boolean;
  IsWatercraftCoverage?: boolean;
  IsWatercraftExposure?: boolean;
  LineOfBusinessId?: string;
  OtherExistingCoverage1?: string;
  OtherExistingCoverage2?: string;
  OtherExistingCoverage3?: string;
  OtherExistingCoverage4?: string;
  PolicyId?: string;
  Status?: string;
  UmbrellaCoverageId?: string;
}
