/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesOtherInsurance {
  CompanyName?: string;
  EffectiveDate?: string;
  LineOfBusiness?: string;
  NAIC?: string;
  OtherInsuranceId?: string;
  PolicyEffectiveDate?: string;
  PolicyExpiryDate?: string;
  PolicyId?: string;
  PolicyNumber?: string;
  StatePlanType?: string;
  Status?: string;
}
