/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPoliciesAddIntrest {
  AdditionalInterestId?: string;
  Address1?: string;
  Address2?: string;
  AttachId?: string;
  AttachType?: number;
  BuildingNumber?: string;
  CertificateIssuedDate?: string;
  CertificateRequiredDate?: string;
  City?: string;
  CommercialBuildingId?: string;
  CommercialLocationId?: string;
  ContactName?: string;
  DescriptionOfOperations?: string;
  EffectiveDate?: string;
  EmailAddress?: string;
  EntityId?: string;
  FarmItemID?: string;
  FaxAreaCode?: string;
  FaxExtension?: string;
  FaxPhone?: string;
  FinalPayDateForLoan?: string;
  FirstName?: string;
  InterestInOther?: string;
  InterestType?: string;
  IsBonded?: boolean;
  IsCertificateIssued?: boolean;
  IsCertificateRequired?: boolean;
  IsLicensed?: boolean;
  IsPayor?: boolean;
  IsPolicyIssued?: boolean;
  IsPolicyRequired?: boolean;
  IsXOutEndeavor?: boolean;
  IsXOutFailure?: boolean;
  IsXOutWorkComp?: boolean;
  ItemDescription?: string;
  JobNumber?: string;
  JobType?: string;
  LastName?: string;
  LineOfBusinessId?: string;
  LocationNumber?: string;
  MethodOfDelivery?: string;
  MiddleName?: string;
  Name1?: string;
  Name2?: string;
  NumberOfDays?: string;
  PhoneAreaCode?: string;
  PhoneExtension?: string;
  PhoneNumber?: string;
  PolicyId?: string;
  PolicyIssuedDate?: string;
  PolicyRequiredDate?: string;
  ProjectEndDate?: string;
  Rank?: string;
  ReferenceId?: string;
  ReferenceNumber?: string;
  ReferenceType?: number;
  State?: string;
  Status?: string;
  Zip?: string;
}
