/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelNewBusinessProducerProductionDto {
  AnnualPremium?: number;
  MonthlyPremium?: number;
  MonthlyPremiumBilled?: number;
  MonthlyPremiumCLOSED?: number;
  MonthlyPremiumOutstanding?: number;
  MonthlyPremiumQuoted?: number;
  NumberOfCustomers?: number;
  NumberOfProspects?: number;
}
