/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSSuspenses {
  CCCodes?: string;
  CCNames?: string;
  CenterName?: string;
  Claim?: string;
  ClaimId?: string;
  CompanyCode?: string;
  CompanyName?: string;
  CompletedBy?: string;
  CompletedByName?: string;
  CompletedDate?: string;
  CustomerId?: string;
  CustomerName?: string;
  DBAction?: string;
  Description?: string;
  DueDate?: string;
  EffectiveDate?: string;
  EntityType?: number;
  InitiateDate?: string;
  IsCompleted?: boolean;
  IsSecuredEntityLink?: boolean;
  IsTruncated?: boolean;
  LastExported?: string;
  PolicyId?: string;
  PolicyNumber?: string;
  PolicyType?: string;
  Priority?: number;
  PriorityDisplay?: string;
  ReferenceType?: number;
  ReschedNo?: string;
  SuspendedByEmployeeCode?: string;
  SuspendedByEmployeeName?: string;
  SuspendedToEmployeeCode?: string;
  SuspendedToEmployeeName?: string;
  SuspenseId?: string;
  TypeOfBusiness?: number;
}
