/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSDrivers {
  AddressLine1?: string;
  AddressLine2?: string;
  City?: string;
  DateOfBirth?: string;
  DefensiveDriverDate?: string;
  DriverId?: string;
  DriverNo?: string;
  EffectiveDate?: string;
  Employer?: string;
  FirstName?: string;
  IsDeferred?: boolean;
  IsDriverTrained?: boolean;
  IsGoodDriver?: boolean;
  IsGoodStudent?: boolean;
  IsMatureDriver?: boolean;
  IsStudentOver?: boolean;
  LastName?: string;
  License?: string;
  LicenseClass?: string;
  LicenseDate?: string;
  LicenseState?: string;
  LineOfBusinessId?: string;
  Married?: string;
  MiddleName?: string;
  Occupation?: string;
  OtherLicenseDate?: string;
  PolicyId?: string;
  Relation?: string;
  Sex?: string;
  SocialSecurityNumber?: string;
  State?: string;
  Status?: string;
  UnlicenseExclude?: string;
  YearEmployed?: string;
  YearLicensed?: string;
  ZipCode?: string;
}
