/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSNotes {
  Claim?: string;
  ClaimId?: string;
  CustomerId?: string;
  CustomerName?: string;
  IsAttachment?: boolean;
  IsSticky?: boolean;
  Note?: string;
  NoteDate?: string;
  NoteId?: string;
  PolicyEffectiveDate?: string;
  PolicyId?: string;
  PolicyNumber?: string;
  Priority?: string;
  PriorityDescription?: string;
  PurgeDate?: string;
  ReferenceId?: string;
  ReferenceType?: number;
  ReferenceTypeDescription?: string;
}
