/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSActivityAction {
  ActionId?: string;
  DBAction?: string;
  DisplayPermanent?: string;
  IsCampaignAction?: boolean;
  IsClaimAction?: boolean;
  IsHide?: boolean;
  IsPolicyAction?: boolean;
  IsSubmissionAction?: boolean;
  NumberOfSuspenseDays?: number;
  PermanentFlag?: number;
  SortNumber?: number;
}
