/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSPolicyTransactions {
  Description?: string;
  EffectiveDate?: string;
  PolEffDate?: string;
  PolExpDate?: string;
  PolicyId?: string;
  PolNo?: string;
  PremiumOnEffectivDate?: number;
  TransactionType?: string;
}
