/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelPropertyInsuredName {
  Balance?: number;
  FinalPremium?: number;
  InsuredName?: string;
  NumberOfInstallments?: number;
}
