/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSEmployeeDocuments {
  Actions?: string;
  AgencyDocumentType?: string;
  AgencyDocumentTypeDescription?: string;
  AssignedByEmployeeCode?: string;
  AssignedByShortName?: string;
  AssignedToEmployeeCode?: string;
  AssignedToShortName?: string;
  CheckOutDate?: string;
  CheckOutEmployeeCode?: string;
  CheckOutLocation?: string;
  ClaimId?: string;
  Comment?: string;
  Description?: string;
  DocumentAttachmentId?: string;
  DocumentClassificationId?: string;
  DocumentRoutingId?: string;
  DocumentType?: number;
  EffectiveDate?: string;
  EncryptKey?: string;
  EntityId?: string;
  EntityName?: string;
  EntityType?: number;
  EntityTypeName?: string;
  FileExtension?: string;
  FileName?: string;
  FilePath?: string;
  ImageId?: string;
  ImageId12?: string;
  ImageId13?: string;
  ImageIdDocumentManagmentVendor?: string;
  Index1?: string;
  Index2?: string;
  IsCompressed?: boolean;
  IsDocumentDeleted?: boolean;
  IsEncrypted?: boolean;
  IsLocked?: boolean;
  IsMessageAttachments?: boolean;
  IsSecured?: boolean;
  IsSecuredEntityLink?: boolean;
  MessageAttachments?: string;
  OriginalSize?: number;
  PolicyId?: string;
  ProcessedBy?: string;
  ProcessedDate?: string;
  ReceivedDate?: string;
  ReferenceNumber?: string;
  ReferencePrefix?: string;
  ReferenceSuffix?: number;
  SourceFileName?: string;
  Status?: string;
  StatusDescription?: string;
  StorageFileName?: string;
  StorageOption?: string;
  StorageOptionDescription?: string;
  StorageSize?: number;
  WorkstationId?: string;
  WorkstationName?: string;
}
