/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelGetGroupTypeEntity {
  AttributeCode?: string;
  Category?: number;
  Description?: string;
  Id?: number;
  IsHide?: boolean;
  PermanentFlag?: number;
  SortNumber?: number;
  Type?: string;
}
