/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSAgencyAddress {
  Address1?: string;
  Address2?: string;
  AddressType?: string;
  AgencyAddressId?: string;
  AgencyId?: string;
  AgencyName?: string;
  AgencyNumber?: string;
  BusinessUnitLogo?: string;
  City?: string;
  Email?: string;
  FaxAreaCode?: string;
  FaxPhone?: string;
  FaxtExtension?: string;
  GeneralLedgerCode?: string;
  Latitude?: number;
  Longitude?: number;
  Name?: string;
  Phone?: string;
  Phone24HrAAddress?: string;
  Phone24HrAreaCodeAAddress?: string;
  Phone24HrExtensionAAddress?: string;
  PhoneAreaCode?: string;
  PhoneExtension?: string;
  State?: string;
  Status?: string;
  WebAddress?: string;
  ZipCode?: string;
}
