/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSProfiles {
  Answer?: string;
  AnswerFormat?: string;
  AnswerLength?: number;
  CustomerId?: string;
  IsCustomerActive?: boolean;
  IsHide?: boolean;
  Question?: string;
  QuestionId?: string;
  TypeOfBusiness?: number;
  TypeOfBusinessDescription?: string;
}
