/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelInsureInvestorsRating {
  AgencyFee?: number;
  CommissionFee?: number;
  CREATEDATE?: string;
  CreatedBy?: number;
  CustomerID?: number;
  CustomFloodRate?: number;
  CustomLiabilityRate?: number;
  CustomRate?: number;
  dblContentsBasePremium?: number;
  dblContentsPremium?: number;
  dblCustomCoverage?: number;
  dblFee?: number;
  dblFloodPremium?: number;
  dblFloodPremiumTax?: number;
  dblLiabilityPremium?: number;
  dblLiabilityPremiumTax?: number;
  dblPremiumSubtotal?: number;
  dblPremiumTax?: number;
  dblPropertyBasePremium?: number;
  dblPropertyPremium?: number;
  dblRate?: number;
  dblRentBasePremium?: number;
  dblRentPremium?: number;
  dblTIVBaseTax?: number;
  dblTotal?: number;
  DeductibleID?: number;
  DownPayment?: number;
  EffectiveDate?: string;
  ExpirationDate?: string;
  FeePercentage?: number;
  FinalPremium?: number;
  InspectionFee?: number;
  InstallmentAmount?: number;
  intArea?: number;
  intContentsCoverage?: number;
  intCoverage?: number;
  intCustomCoverageAmount?: number;
  intFloodCoverage?: number;
  intLiabilityID?: number;
  intPropertyTypeID?: number;
  intRentCoverage?: number;
  intValuationTypeID?: number;
  IsBulkPricing?: boolean;
  IsCustomRating?: number;
  IsFeesWaived?: boolean;
  ModifiedBy?: number;
  MODIFYDATE?: string;
  NumberOfProperties?: number;
  NumberOfStories?: number;
  NumberOfUnits?: number;
  PolicyBaseRate?: number;
  PropertyID?: number;
  QuoteBaseRate?: number;
  Rate?: number;
  selectedCoverage?: number;
  TransactionType?: string;
  WholesaleBaseRate?: number;
  WritingCompanyID?: number;
  YearBuilt?: number;
  Zipcode?: string;
}
