/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelMemberActivityDto {
  AGENTID?: number;
  ClosingRatio?: number;
  Earn?: number;
  FIRSTNAME?: string;
  LASTNAME?: string;
  MonthlyPremiumQuoted?: number;
  NumberOfCustomers?: number;
  NumberOfProspects?: number;
  PremiumWon?: number;
}
