/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSVehicleStorage {
  EffectiveDate?: string;
  GarageDealerStorageId?: string;
  GarageId?: string;
  GarageNumber?: string;
  GarageRiskCode?: string;
  LineOfBusinessId?: string;
  PhysicalDamagePeriodCode?: string;
  PolicyId?: string;
  Scehduled?: string;
  Status?: string;
  StorageLimit?: number;
  Type?: string;
}
