/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSLossOfHistoryPolicies {
  AmountPaid?: number;
  AmountReserved?: number;
  AnnualPremiumLossHistory?: number;
  ClaimStatus?: string;
  CompanyName?: string;
  DateOfLoss?: string;
  EffectiveDate?: string;
  KindOfLoss?: string;
  LineOfBusiness?: string;
  LineOfBusinessId?: string;
  LossDateNote?: string;
  LossDescription?: string;
  LossHistoryId?: string;
  ModificationLossHistory?: number;
  NAICLossHistory?: string;
  NumberOfClaimsLossHistory?: number;
  PolicyEffectiveDate?: string;
  PolicyExpiryDate?: string;
  PolicyId?: string;
  PolicyNumber?: string;
  ReportDate?: string;
  Status?: string;
}
