/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface DomainModelAMSModelAMSCommercialUmbrellaVehicle {
  EffectiveDate?: string;
  LineOfBusinessId?: string;
  Miles0To50?: string;
  Miles50To200?: string;
  MilesOver200?: string;
  NumberOfLeased?: string;
  NumberOfNonOwned?: string;
  NumberOfOwned?: string;
  PolicyId?: string;
  PropertyHauled?: string;
  Status?: string;
  UmbrellaVehicleId?: string;
  VehicleType?: string;
}
