/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export type PaymentProcessingCustomerInsureInvestorsPaymentBankAccountParams = {
'paymentProcessBankAccount.iD'?: number;
'paymentProcessBankAccount.cardNumber'?: string;
'paymentProcessBankAccount.invoiceID'?: string;
'paymentProcessBankAccount.amount'?: number;
'paymentProcessBankAccount.expiryMonth'?: string;
'paymentProcessBankAccount.expiryYear'?: string;
'paymentProcessBankAccount.cVV'?: string;
'paymentProcessBankAccount.cardHolder'?: string;
'paymentProcessBankAccount.startDate'?: string;
'paymentProcessBankAccount.customerID'?: number;
'paymentProcessBankAccount.aGENTID'?: number;
'paymentProcessBankAccount.fIRSTNAME'?: string;
'paymentProcessBankAccount.lASTNAME'?: string;
'paymentProcessBankAccount.uSERNAME'?: string;
'paymentProcessBankAccount.pASSWORD'?: string;
'paymentProcessBankAccount.cOMPANY'?: string;
'paymentProcessBankAccount.aDDRESS1'?: string;
'paymentProcessBankAccount.aDDRESS2'?: string;
'paymentProcessBankAccount.cITY'?: string;
'paymentProcessBankAccount.sTATEID'?: number;
'paymentProcessBankAccount.sTATE'?: string;
'paymentProcessBankAccount.zIPCODE'?: string;
'paymentProcessBankAccount.eMAIL'?: string;
'paymentProcessBankAccount.pHONE'?: string;
'paymentProcessBankAccount.invoiceNo'?: string;
'paymentProcessBankAccount.description'?: string;
'paymentProcessBankAccount.paymentMethodName'?: string;
'paymentProcessBankAccount.accountType'?: string;
'paymentProcessBankAccount.routingNumber'?: string;
'paymentProcessBankAccount.accountNumber'?: string;
'paymentProcessBankAccount.nameOnAccount'?: string;
'paymentProcessBankAccount.echeckType'?: string;
'paymentProcessBankAccount.bankName'?: string;
'paymentProcessBankAccount.recurringID'?: number;
'paymentProcessBankAccount.tokenID'?: string;
};
