/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export type PaymentProcessingThanksEmailTemplateParams = {
CustomerName: string;
CustomerAmount: string;
};
