/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export type PaymentProcessingCustomerInsureInvestorsPaymentCreditCardParams = {
'paymentProcessCreditCard.iD'?: number;
'paymentProcessCreditCard.cardNumber'?: string;
'paymentProcessCreditCard.invoiceID'?: string;
'paymentProcessCreditCard.amount'?: number;
'paymentProcessCreditCard.expiryMonth'?: string;
'paymentProcessCreditCard.expiryYear'?: string;
'paymentProcessCreditCard.cVV'?: string;
'paymentProcessCreditCard.cardHolder'?: string;
'paymentProcessCreditCard.startDate'?: string;
'paymentProcessCreditCard.customerID'?: number;
'paymentProcessCreditCard.aGENTID'?: number;
'paymentProcessCreditCard.fIRSTNAME'?: string;
'paymentProcessCreditCard.lASTNAME'?: string;
'paymentProcessCreditCard.uSERNAME'?: string;
'paymentProcessCreditCard.pASSWORD'?: string;
'paymentProcessCreditCard.cOMPANY'?: string;
'paymentProcessCreditCard.aDDRESS1'?: string;
'paymentProcessCreditCard.aDDRESS2'?: string;
'paymentProcessCreditCard.cITY'?: string;
'paymentProcessCreditCard.sTATEID'?: number;
'paymentProcessCreditCard.sTATE'?: string;
'paymentProcessCreditCard.zIPCODE'?: string;
'paymentProcessCreditCard.eMAIL'?: string;
'paymentProcessCreditCard.pHONE'?: string;
'paymentProcessCreditCard.invoiceNo'?: string;
'paymentProcessCreditCard.description'?: string;
'paymentProcessCreditCard.paymentMethodName'?: string;
'paymentProcessCreditCard.accountType'?: string;
'paymentProcessCreditCard.routingNumber'?: string;
'paymentProcessCreditCard.accountNumber'?: string;
'paymentProcessCreditCard.nameOnAccount'?: string;
'paymentProcessCreditCard.echeckType'?: string;
'paymentProcessCreditCard.bankName'?: string;
'paymentProcessCreditCard.recurringID'?: number;
'paymentProcessCreditCard.tokenID'?: string;
};
