/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export type PDFCreatorCustomerWelcomeEmailWithClientPortalAccess200One = { [key: string]: any };
