/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export type PDFCreatorGenericEmailTemplateByCustomerInfoParams = {
amount: number;
Title?: string;
BodyText1?: string;
'Customer.policyNumber'?: string;
'Customer.feePercentage'?: number;
'Customer.chargebeeSubscriptionId'?: string;
'Customer.chargebeeCustomerId'?: string;
'Customer.referralID'?: number;
'Customer.deductibleID'?: number;
'Customer.uNDERWRITERID'?: number;
'Customer.writingCompanyID'?: number;
'Customer.cUSTOMERID'?: number;
'Customer.aCCOUNTID'?: number;
'Customer.aGENTID'?: number;
'Customer.fIRSTNAME'?: string;
'Customer.lASTNAME'?: string;
'Customer.uSERNAME'?: string;
'Customer.pASSWORD'?: string;
'Customer.cOMPANY'?: string;
'Customer.aDDRESS1'?: string;
'Customer.aDDRESS2'?: string;
'Customer.cITY'?: string;
'Customer.sTATEID'?: number;
'Customer.state'?: string;
'Customer.zIPCODE'?: string;
'Customer.eMAIL'?: string;
'Customer.pHONE'?: string;
'Customer.eFFECTIVEDATE'?: string;
'Customer.eXPIRATIONDATE'?: string;
'Customer.sTATUSID'?: number;
'Customer.uNIQUEKEY'?: string;
'Customer.cREATEDATE'?: string;
'Customer.mODIFYDATE'?: string;
'Customer.bILLINGOPTIONID'?: number;
'Customer.createdBy'?: number;
'Customer.modifiedBy'?: number;
'Customer.floodPolicyNumber'?: string;
'Customer.liabilityPolicyNumber'?: string;
'Customer.isAuthenticated'?: boolean;
'Customer.isBulkUpload'?: boolean;
'Customer.tokenID'?: string;
'Customer.lIABILITYID'?: number;
'Customer.profilePictureUrl'?: string;
'Customer.accountStatus'?: number;
'Customer.transactionTypeId'?: number;
'Customer.totalPayment'?: number;
'Customer.totalPremium'?: number;
'Customer.balance'?: number;
'Customer.isProcessed'?: number;
'Customer.isFeesWaived'?: boolean;
'Customer.customLiabilityPremium'?: number;
'Customer.customFloodRate'?: number;
'Customer.wholesaleLiabilityPremium'?: number;
'Customer.isDirectBilled'?: boolean;
'Customer.allPerilsDeductible'?: number;
'Customer.allPerilsDeductiblePerBuilding'?: boolean;
'Customer.allPerilsDeductiblePerOccurence'?: boolean;
'Customer.windDeductible'?: number;
'Customer.windDeductiblePerBuilding'?: boolean;
'Customer.windDeductiblePerOccurence'?: boolean;
'Customer.namedStormDeductible'?: number;
'Customer.namedStormDeductiblePerBuilding'?: boolean;
'Customer.namedStormDeductiblePerOccurence'?: boolean;
'Customer.liabilityDeductible'?: number;
'Customer.coInsurance'?: number;
'Customer.isNew'?: boolean;
'Customer.paymentMethodId'?: number;
'Customer.isRecurring'?: boolean;
'Customer.numberOfInstallments'?: number;
'Customer.numberOfRemainingInstallments'?: number;
'Customer.inspectionFee'?: number;
'Customer.commissionFee'?: number;
'Customer.customerProfileId'?: string;
'Customer.customPropertyRate'?: number;
};
