/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { PDFCreatorSendToCustomerDataBodyOne } from './pDFCreatorSendToCustomerDataBodyOne';
import type { PDFCreatorSendToCustomerDataBodyTwo } from './pDFCreatorSendToCustomerDataBodyTwo';
import type { PDFCreatorSendToCustomerDataBodyThree } from './pDFCreatorSendToCustomerDataBodyThree';
import type { PDFCreatorSendToCustomerDataBodyFour } from './pDFCreatorSendToCustomerDataBodyFour';
import type { PDFCreatorSendToCustomerDataBodyFive } from './pDFCreatorSendToCustomerDataBodyFive';

export type PDFCreatorSendToCustomerDataBody = PDFCreatorSendToCustomerDataBodyOne | PDFCreatorSendToCustomerDataBodyTwo | PDFCreatorSendToCustomerDataBodyThree | PDFCreatorSendToCustomerDataBodyFour | PDFCreatorSendToCustomerDataBodyFive;
