/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelRecurringSubscription } from './domainModelRecurringSubscription';

export interface ProvidersSPHelperGenericRecordListDomainModelRecurringSubscription {
  RecordList?: DomainModelRecurringSubscription[];
  TotalRecords?: number;
}
