/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelPaymentProcessTransaction } from './domainModelPaymentProcessTransaction';

export interface ProvidersSPHelperGenericRecordListDomainModelPaymentProcessTransaction {
  RecordList?: DomainModelPaymentProcessTransaction[];
  TotalRecords?: number;
}
