/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { DomainModelVMInvoicePropertyDetails } from './domainModelVMInvoicePropertyDetails';

export interface ProvidersSPHelperGenericRecordListDomainModelVMInvoicePropertyDetails {
  RecordList?: DomainModelVMInvoicePropertyDetails[];
  TotalRecords?: number;
}
