/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export interface SystemIOStream {
  readonly CanRead?: boolean;
  readonly CanSeek?: boolean;
  readonly CanTimeout?: boolean;
  readonly CanWrite?: boolean;
  readonly Length?: number;
  Position?: number;
  ReadTimeout?: number;
  WriteTimeout?: number;
}
