/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */

export type UserPutUserParams = {
'user.id'?: number;
'user.accountID'?: number;
'user.firstName'?: string;
'user.lastName'?: string;
'user.userName'?: string;
'user.password'?: string;
'user.cREATEDATE'?: string;
'user.mODIFYDATE'?: string;
'user.createdBy'?: number;
'user.modifiedBy'?: number;
'user.profilePictureUrl'?: string;
};
