/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Insure Investors API
 * OpenAPI spec version: v1
 */
import type { WebAppModelsExternalLoginViewModel } from './webAppModelsExternalLoginViewModel';
import type { WebAppModelsUserLoginInfoViewModel } from './webAppModelsUserLoginInfoViewModel';

export interface WebAppModelsManageInfoViewModel {
  Email?: string;
  ExternalLoginProviders?: WebAppModelsExternalLoginViewModel[];
  LocalLoginProvider?: string;
  Logins?: WebAppModelsUserLoginInfoViewModel[];
}
